/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_chi_dof_0ac82e16.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_chi_dof_0ac82e16.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.chi_dof_0ac82e16
 * ORIGIN SYMBOL:    purce_test.chi_dof
 * ORIGIN FILE:      purce_test:647
 * ORIGIN SIGNATURE: float64 n_minus -> float64 one -> float64
 *
 * MATH INTENT:
 *   Function 'chi_dof' composed of: element_max
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.maximum as element_max kernel (from: numpy.maximum)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_chi_dof_0ac82e16(int n, const double * restrict n_minus, const double * restrict one, double * restrict result) {
    /* Element-wise maximum: result[i] = max(n_minus[i], one[i]) */
    for (int i = 0; i < n; i++) {
        result[i] = (n_minus[i] > one[i]) ? n_minus[i] : one[i];
    }
}
