/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_welch_sqrt_n_e1429177.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_welch_sqrt_n_e1429177.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.welch_sqrt_n_e1429177
 * ORIGIN SYMBOL:    purce_test.welch_sqrt_n
 * ORIGIN FILE:      purce_test:765
 * ORIGIN SIGNATURE: float64 n -> float64
 *
 * MATH INTENT:
 *   Function 'welch_sqrt_n' composed of: element_sqrt
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.sqrt as element_sqrt kernel (from: numpy.sqrt)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_welch_sqrt_n_e1429177(int n_len, const double * restrict n, double * restrict result) {
    /* Element-wise square root: result[i] = sqrt(n[i]) */
    for (int i = 0; i < n_len; i++) {
        result[i] = sqrt(n[i]);
    }
}
