/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_depths_resid_1cc49286.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_depths_resid_1cc49286.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.depths_resid_1cc49286
 * ORIGIN SYMBOL:    purce_test.depths_resid
 * ORIGIN FILE:      purce_test:711
 * ORIGIN SIGNATURE: float64 depths -> float64 mu -> float64
 *
 * MATH INTENT:
 *   Function 'depths_resid' composed of: element_sub
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.subtract as element_sub kernel (from: numpy.subtract)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_depths_resid_1cc49286(int n, const double * restrict depths, const double * restrict mu, double * restrict result) {
    /* Element-wise subtraction: result[i] = depths[i] - mu[i] */
    for (int i = 0; i < n; i++) {
        result[i] = depths[i] - mu[i];
    }
}
