/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_welch_delta_cb20ee08.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_welch_delta_cb20ee08.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.welch_delta_cb20ee08
 * ORIGIN SYMBOL:    purce_test.welch_delta
 * ORIGIN FILE:      purce_test:775
 * ORIGIN SIGNATURE: float64 mu_e -> float64 mu_o -> float64
 *
 * MATH INTENT:
 *   Function 'welch_delta' composed of: element_sub
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.subtract as element_sub kernel (from: numpy.subtract)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_welch_delta_cb20ee08(int n, const double * restrict mu_e, const double * restrict mu_o, double * restrict result) {
    /* Element-wise subtraction: result[i] = mu_e[i] - mu_o[i] */
    for (int i = 0; i < n; i++) {
        result[i] = mu_e[i] - mu_o[i];
    }
}
