/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_depth_cons_chi_sub_292b7f19.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_depth_cons_chi_sub_292b7f19.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.depth_cons_chi_sub_292b7f19
 * ORIGIN SYMBOL:    purce_test.depth_cons_chi_sub
 * ORIGIN FILE:      purce_test:736
 * ORIGIN SIGNATURE: float64 chi2_red -> float64 one -> float64
 *
 * MATH INTENT:
 *   Function 'depth_cons_chi_sub' composed of: element_sub
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.subtract as element_sub kernel (from: numpy.subtract)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_depth_cons_chi_sub_292b7f19(int n, const double * restrict chi2_red, const double * restrict one, double * restrict result) {
    /* Element-wise subtraction: result[i] = chi2_red[i] - one[i] */
    for (int i = 0; i < n; i++) {
        result[i] = chi2_red[i] - one[i];
    }
}
