/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_probability_ptr_clamped_24b013a4.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_probability_ptr_clamped_24b013a4.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.probability_ptr_clamped_24b013a4
 * ORIGIN SYMBOL:    purce_test.probability_ptr_clamped
 * ORIGIN FILE:      purce_test:447
 * ORIGIN SIGNATURE: float64 ptr -> float64 one -> float64
 *
 * MATH INTENT:
 *   Function 'probability_ptr_clamped' composed of: element_min
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.minimum as element_min kernel (from: numpy.minimum)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_probability_ptr_clamped_24b013a4(int n, const double * restrict ptr, const double * restrict one, double * restrict result) {
    /* Element-wise minimum: result[i] = min(ptr[i], one[i]) */
    for (int i = 0; i < n; i++) {
        result[i] = (ptr[i] < one[i]) ? ptr[i] : one[i];
    }
}
