/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_depth_cons_norm_sub_f903e415.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_depth_cons_norm_sub_f903e415.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.depth_cons_norm_sub_f903e415
 * ORIGIN SYMBOL:    purce_test.depth_cons_norm_sub
 * ORIGIN FILE:      purce_test:741
 * ORIGIN SIGNATURE: float64 norm -> float64 one -> float64
 *
 * MATH INTENT:
 *   Function 'depth_cons_norm_sub' composed of: element_sub
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.subtract as element_sub kernel (from: numpy.subtract)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_depth_cons_norm_sub_f903e415(int n, const double * restrict norm, const double * restrict one, double * restrict result) {
    /* Element-wise subtraction: result[i] = norm[i] - one[i] */
    for (int i = 0; i < n; i++) {
        result[i] = norm[i] - one[i];
    }
}
