/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_geometry_cons_resid_abs_ada5525d.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_geometry_cons_resid_abs_ada5525d.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.geometry_cons_resid_abs_ada5525d
 * ORIGIN SYMBOL:    purce_test.geometry_cons_resid_abs
 * ORIGIN FILE:      purce_test:274
 * ORIGIN SIGNATURE: float64 sub -> float64
 *
 * MATH INTENT:
 *   Function 'geometry_cons_resid_abs' composed of: element_abs
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.abs as element_abs kernel (from: numpy.abs)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_geometry_cons_resid_abs_ada5525d(int n, const double * restrict sub, double * restrict result) {
    /* Element-wise absolute value: result[i] = fabs(sub[i]) */
    for (int i = 0; i < n; i++) {
        result[i] = fabs(sub[i]);
    }
}
