/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_chi_n_minus_889c185a.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_chi_n_minus_889c185a.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.chi_n_minus_889c185a
 * ORIGIN SYMBOL:    purce_test.chi_n_minus
 * ORIGIN FILE:      purce_test:642
 * ORIGIN SIGNATURE: float64 n -> float64 one -> float64
 *
 * MATH INTENT:
 *   Function 'chi_n_minus' composed of: element_sub
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.subtract as element_sub kernel (from: numpy.subtract)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_chi_n_minus_889c185a(int n_len, const double * restrict n, const double * restrict one, double * restrict result) {
    /* Element-wise subtraction: result[i] = n[i] - one[i] */
    for (int i = 0; i < n_len; i++) {
        result[i] = n[i] - one[i];
    }
}
