/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_depth_cons_ratio_a638f61f.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_depth_cons_ratio_a638f61f.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.depth_cons_ratio_a638f61f
 * ORIGIN SYMBOL:    purce_test.depth_cons_ratio
 * ORIGIN FILE:      purce_test:746
 * ORIGIN SIGNATURE: float64 chi_sub -> float64 norm_sub -> float64
 *
 * MATH INTENT:
 *   Function 'depth_cons_ratio' composed of: element_div
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.divide as element_div kernel (from: numpy.divide)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_depth_cons_ratio_a638f61f(int n, const double * restrict chi_sub, const double * restrict norm_sub, double * restrict result) {
    /* Element-wise division: result[i] = chi_sub[i] / norm_sub[i] (IEEE 754: x/0 = +/-inf, 0/0 = NaN) */
    for (int i = 0; i < n; i++) {
        result[i] = chi_sub[i] / norm_sub[i];
    }
}
