/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_geometry_cons_k_sq_max_22b169b0.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_geometry_cons_k_sq_max_22b169b0.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.geometry_cons_k_sq_max_22b169b0
 * ORIGIN SYMBOL:    purce_test.geometry_cons_k_sq_max
 * ORIGIN FILE:      purce_test:279
 * ORIGIN SIGNATURE: float64 k_sq -> float64 eps -> float64
 *
 * MATH INTENT:
 *   Function 'geometry_cons_k_sq_max' composed of: element_max
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.maximum as element_max kernel (from: numpy.maximum)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_geometry_cons_k_sq_max_22b169b0(int n, const double * restrict k_sq, const double * restrict eps, double * restrict result) {
    /* Element-wise maximum: result[i] = max(k_sq[i], eps[i]) */
    for (int i = 0; i < n; i++) {
        result[i] = (k_sq[i] > eps[i]) ? k_sq[i] : eps[i];
    }
}
