/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_depths_ratio_b076a040.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_depths_ratio_b076a040.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.depths_ratio_b076a040
 * ORIGIN SYMBOL:    purce_test.depths_ratio
 * ORIGIN FILE:      purce_test:726
 * ORIGIN SIGNATURE: float64 resid_sq -> float64 err_sq -> float64
 *
 * MATH INTENT:
 *   Function 'depths_ratio' composed of: element_div
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.divide as element_div kernel (from: numpy.divide)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_depths_ratio_b076a040(int n, const double * restrict resid_sq, const double * restrict err_sq, double * restrict result) {
    /* Element-wise division: result[i] = resid_sq[i] / err_sq[i] (IEEE 754: x/0 = +/-inf, 0/0 = NaN) */
    for (int i = 0; i < n; i++) {
        result[i] = resid_sq[i] / err_sq[i];
    }
}
