/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_depth_consistency_s_5acee7ef.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_depth_consistency_s_5acee7ef.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.depth_consistency_s_5acee7ef
 * ORIGIN SYMBOL:    purce_test.depth_consistency_s
 * ORIGIN FILE:      purce_test:756
 * ORIGIN SIGNATURE: float64 sub -> float64 zero -> float64 one -> float64
 *
 * MATH INTENT:
 *   Function 'depth_consistency_s' composed of: element_clip
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.clip as element_clip kernel (from: numpy.clip)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_depth_consistency_s_5acee7ef(int n, const double * restrict sub, const double * restrict zero, const double * restrict one, double * restrict result) {
    /* Element-wise clip: result[i] = min(max(sub[i], zero[i]), one[i]) */
    for (int i = 0; i < n; i++) {
        double v = sub[i];
        result[i] = (v < zero[i]) ? zero[i] : (v > one[i]) ? one[i] : v;
    }
}
