/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_density_logg_8fde41c0.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_density_logg_8fde41c0.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.density_logg_8fde41c0
 * ORIGIN SYMBOL:    purce_test.density_logg
 * ORIGIN FILE:      purce_test:423
 * ORIGIN SIGNATURE: float64 g_cgs_max -> float64
 *
 * MATH INTENT:
 *   Function 'density_logg' composed of: element_log10
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.log10 as element_log10 kernel (from: numpy.log10)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_density_logg_8fde41c0(int n, const double * restrict g_cgs_max, double * restrict result) {
    /* Element-wise base-10 log: result[i] = log10(g_cgs_max[i]) */
    for (int i = 0; i < n; i++) {
        result[i] = log10(g_cgs_max[i]);
    }
}
