/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_density_rho_tic_gcc_44b154cc.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_density_rho_tic_gcc_44b154cc.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.density_rho_tic_gcc_44b154cc
 * ORIGIN SYMBOL:    purce_test.density_rho_tic_gcc
 * ORIGIN FILE:      purce_test:383
 * ORIGIN SIGNATURE: float64 rho_kgm3 -> float64 inv1000 -> float64
 *
 * MATH INTENT:
 *   Function 'density_rho_tic_gcc' composed of: element_mul
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.multiply as element_mul kernel (from: numpy.multiply)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_density_rho_tic_gcc_44b154cc(int n, const double * restrict rho_kgm3, const double * restrict inv1000, double * restrict result) {
    /* Element-wise multiplication: result[i] = rho_kgm3[i] * inv1000[i] */
    for (int i = 0; i < n; i++) {
        result[i] = rho_kgm3[i] * inv1000[i];
    }
}
