/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_geometry_cons_resid_pct_abd2b692.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_geometry_cons_resid_pct_abd2b692.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.geometry_cons_resid_pct_abd2b692
 * ORIGIN SYMBOL:    purce_test.geometry_cons_resid_pct
 * ORIGIN FILE:      purce_test:289
 * ORIGIN SIGNATURE: float64 residual -> float64 hundred -> float64
 *
 * MATH INTENT:
 *   Function 'geometry_cons_resid_pct' composed of: element_mul
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.multiply as element_mul kernel (from: numpy.multiply)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_geometry_cons_resid_pct_abd2b692(int n, const double * restrict residual, const double * restrict hundred, double * restrict result) {
    /* Element-wise multiplication: result[i] = residual[i] * hundred[i] */
    for (int i = 0; i < n; i++) {
        result[i] = residual[i] * hundred[i];
    }
}
