/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_kepler_denominator_4590064a.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_kepler_denominator_4590064a.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.kepler_denominator_4590064a
 * ORIGIN SYMBOL:    purce_test.kepler_denominator
 * ORIGIN FILE:      purce_test:64
 * ORIGIN SIGNATURE: float64 four -> float64 pi_sq -> float64
 *
 * MATH INTENT:
 *   Function 'kepler_denominator' composed of: element_mul
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.multiply as element_mul kernel (from: numpy.multiply)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_kepler_denominator_4590064a(int n, const double * restrict four, const double * restrict pi_sq, double * restrict result) {
    /* Element-wise multiplication: result[i] = four[i] * pi_sq[i] */
    for (int i = 0; i < n; i++) {
        result[i] = four[i] * pi_sq[i];
    }
}
