/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_probability_b_sq_cb568370.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_probability_b_sq_cb568370.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.probability_b_sq_cb568370
 * ORIGIN SYMBOL:    purce_test.probability_b_sq
 * ORIGIN FILE:      purce_test:507
 * ORIGIN SIGNATURE: float64 opk_sq -> float64 st_sq -> float64
 *
 * MATH INTENT:
 *   Function 'probability_b_sq' composed of: element_sub
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.subtract as element_sub kernel (from: numpy.subtract)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_probability_b_sq_cb568370(int n, const double * restrict opk_sq, const double * restrict st_sq, double * restrict result) {
    /* Element-wise subtraction: result[i] = opk_sq[i] - st_sq[i] */
    for (int i = 0; i < n; i++) {
        result[i] = opk_sq[i] - st_sq[i];
    }
}
