/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_depths_std_scale2_2124da6a.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_depths_std_scale2_2124da6a.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.depths_std_scale2_2124da6a
 * ORIGIN SYMBOL:    purce_test.depths_std_scale2
 * ORIGIN FILE:      purce_test:691
 * ORIGIN SIGNATURE: float64 scaled -> float64 inv_nm1 -> float64
 *
 * MATH INTENT:
 *   Function 'depths_std_scale2' composed of: element_mul
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.multiply as element_mul kernel (from: numpy.multiply)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_depths_std_scale2_2124da6a(int n, const double * restrict scaled, const double * restrict inv_nm1, double * restrict result) {
    /* Element-wise multiplication: result[i] = scaled[i] * inv_nm1[i] */
    for (int i = 0; i < n; i++) {
        result[i] = scaled[i] * inv_nm1[i];
    }
}
