/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_geometry_ld_u1cen_term_145d8e8d.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_geometry_ld_u1cen_term_145d8e8d.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.geometry_ld_u1cen_term_145d8e8d
 * ORIGIN SYMBOL:    purce_test.geometry_ld_u1cen_term
 * ORIGIN FILE:      purce_test:234
 * ORIGIN SIGNATURE: float64 u1 -> float64 zeropow -> float64
 *
 * MATH INTENT:
 *   Function 'geometry_ld_u1cen_term' composed of: element_mul
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.multiply as element_mul kernel (from: numpy.multiply)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_geometry_ld_u1cen_term_145d8e8d(int n, const double * restrict u1, const double * restrict zeropow, double * restrict result) {
    /* Element-wise multiplication: result[i] = u1[i] * zeropow[i] */
    for (int i = 0; i < n; i++) {
        result[i] = u1[i] * zeropow[i];
    }
}
