/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_probability_num_3c729ce1.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_probability_num_3c729ce1.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.probability_num_3c729ce1
 * ORIGIN SYMBOL:    purce_test.probability_num
 * ORIGIN FILE:      purce_test:432
 * ORIGIN SIGNATURE: float64 R_star -> float64 R_planet -> float64
 *
 * MATH INTENT:
 *   Function 'probability_num' composed of: element_add
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.add as element_add kernel (from: numpy.add)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_probability_num_3c729ce1(int n, const double * restrict R_star, const double * restrict R_planet, double * restrict result) {
    /* Element-wise addition: result[i] = R_star[i] + R_planet[i] */
    for (int i = 0; i < n; i++) {
        result[i] = R_star[i] + R_planet[i];
    }
}
