/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_probability_p_max_bf57245f.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_probability_p_max_bf57245f.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.probability_p_max_bf57245f
 * ORIGIN SYMBOL:    purce_test.probability_p_max
 * ORIGIN FILE:      purce_test:462
 * ORIGIN SIGNATURE: float64 P_sec -> float64 one -> float64
 *
 * MATH INTENT:
 *   Function 'probability_p_max' composed of: element_max
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.maximum as element_max kernel (from: numpy.maximum)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_probability_p_max_bf57245f(int n, const double * restrict P_sec, const double * restrict one, double * restrict result) {
    /* Element-wise maximum: result[i] = max(P_sec[i], one[i]) */
    for (int i = 0; i < n; i++) {
        result[i] = (P_sec[i] > one[i]) ? P_sec[i] : one[i];
    }
}
