/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_kepler_ratio_solar_412e3aff.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_kepler_ratio_solar_412e3aff.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.kepler_ratio_solar_412e3aff
 * ORIGIN SYMBOL:    purce_test.kepler_ratio_solar
 * ORIGIN FILE:      purce_test:144
 * ORIGIN SIGNATURE: float64 p_yr_sq -> float64 a_au_max -> float64
 *
 * MATH INTENT:
 *   Function 'kepler_ratio_solar' composed of: element_div
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.divide as element_div kernel (from: numpy.divide)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_kepler_ratio_solar_412e3aff(int n, const double * restrict p_yr_sq, const double * restrict a_au_max, double * restrict result) {
    /* Element-wise division: result[i] = p_yr_sq[i] / a_au_max[i] (IEEE 754: x/0 = +/-inf, 0/0 = NaN) */
    for (int i = 0; i < n; i++) {
        result[i] = p_yr_sq[i] / a_au_max[i];
    }
}
