/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_welch_var_sum_626abb29.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_welch_var_sum_626abb29.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.welch_var_sum_626abb29
 * ORIGIN SYMBOL:    purce_test.welch_var_sum
 * ORIGIN FILE:      purce_test:795
 * ORIGIN SIGNATURE: float64 se_e_sq -> float64 se_o_sq -> float64
 *
 * MATH INTENT:
 *   Function 'welch_var_sum' composed of: element_add
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.add as element_add kernel (from: numpy.add)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_welch_var_sum_626abb29(int n, const double * restrict se_e_sq, const double * restrict se_o_sq, double * restrict result) {
    /* Element-wise addition: result[i] = se_e_sq[i] + se_o_sq[i] */
    for (int i = 0; i < n; i++) {
        result[i] = se_e_sq[i] + se_o_sq[i];
    }
}
