/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_chi_squared_688c91db.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_chi_squared_688c91db.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.chi_squared_688c91db
 * ORIGIN SYMBOL:    purce_test.chi_squared
 * ORIGIN FILE:      purce_test:637
 * ORIGIN SIGNATURE: float64 resid_sq -> float64
 *
 * MATH INTENT:
 *   Function 'chi_squared' composed of: reduce_sum
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.sum as reduce_sum kernel (from: numpy.sum)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_chi_squared_688c91db(int n, const double * restrict resid_sq, double * restrict result) {
    /* Reduction sum: result = sum(resid_sq[0..n-1]) */
    double sum = 0.0;
    for (int i = 0; i < n; i++) {
        sum += resid_sq[i];
    }
    *result = sum;
}
