/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_density_rho_transit_kgm3_7f726358.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_density_rho_transit_kgm3_7f726358.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.density_rho_transit_kgm3_7f726358
 * ORIGIN SYMBOL:    purce_test.density_rho_transit_kgm3
 * ORIGIN FILE:      purce_test:353
 * ORIGIN SIGNATURE: float64 coeff -> float64 rho_pow -> float64
 *
 * MATH INTENT:
 *   Function 'density_rho_transit_kgm3' composed of: element_mul
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.multiply as element_mul kernel (from: numpy.multiply)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_density_rho_transit_kgm3_7f726358(int n, const double * restrict coeff, const double * restrict rho_pow, double * restrict result) {
    /* Element-wise multiplication: result[i] = coeff[i] * rho_pow[i] */
    for (int i = 0; i < n; i++) {
        result[i] = coeff[i] * rho_pow[i];
    }
}
