/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_density_a_over_rs_num_e28e6d77.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_density_a_over_rs_num_e28e6d77.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.density_a_over_rs_num_e28e6d77
 * ORIGIN SYMBOL:    purce_test.density_a_over_rs_num
 * ORIGIN FILE:      purce_test:318
 * ORIGIN SIGNATURE: float64 P_sec -> float64 one_plus_k -> float64
 *
 * MATH INTENT:
 *   Function 'density_a_over_rs_num' composed of: element_mul
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.multiply as element_mul kernel (from: numpy.multiply)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_density_a_over_rs_num_e28e6d77(int n, const double * restrict P_sec, const double * restrict one_plus_k, double * restrict result) {
    /* Element-wise multiplication: result[i] = P_sec[i] * one_plus_k[i] */
    for (int i = 0; i < n; i++) {
        result[i] = P_sec[i] * one_plus_k[i];
    }
}
