/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_kepler_gm_f676df7d.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_kepler_gm_f676df7d.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.kepler_gm_f676df7d
 * ORIGIN SYMBOL:    purce_test.kepler_gm
 * ORIGIN FILE:      purce_test:39
 * ORIGIN SIGNATURE: float64 G -> float64 M_star_solar -> float64
 *
 * MATH INTENT:
 *   Function 'kepler_gm' composed of: element_mul
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.multiply as element_mul kernel (from: numpy.multiply)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_kepler_gm_f676df7d(int n, const double * restrict G, const double * restrict M_star_solar, double * restrict result) {
    /* Element-wise multiplication: result[i] = G[i] * M_star_solar[i] */
    for (int i = 0; i < n; i++) {
        result[i] = G[i] * M_star_solar[i];
    }
}
