/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_probability_den_25d25124.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_probability_den_25d25124.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.probability_den_25d25124
 * ORIGIN SYMBOL:    purce_test.probability_den
 * ORIGIN FILE:      purce_test:437
 * ORIGIN SIGNATURE: float64 a_m -> float64 num -> float64
 *
 * MATH INTENT:
 *   Function 'probability_den' composed of: element_max
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.maximum as element_max kernel (from: numpy.maximum)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_probability_den_25d25124(int n, const double * restrict a_m, const double * restrict num, double * restrict result) {
    /* Element-wise maximum: result[i] = max(a_m[i], num[i]) */
    for (int i = 0; i < n; i++) {
        result[i] = (a_m[i] > num[i]) ? a_m[i] : num[i];
    }
}
