/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_geometry_ld_i_mean_8efa5ea4.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_geometry_ld_i_mean_8efa5ea4.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.geometry_ld_i_mean_8efa5ea4
 * ORIGIN SYMBOL:    purce_test.geometry_ld_i_mean
 * ORIGIN FILE:      purce_test:219
 * ORIGIN SIGNATURE: float64 one_minus_both -> float64 min_floor -> float64
 *
 * MATH INTENT:
 *   Function 'geometry_ld_i_mean' composed of: element_max
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.maximum as element_max kernel (from: numpy.maximum)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_geometry_ld_i_mean_8efa5ea4(int n, const double * restrict one_minus_both, const double * restrict min_floor, double * restrict result) {
    /* Element-wise maximum: result[i] = max(one_minus_both[i], min_floor[i]) */
    for (int i = 0; i < n; i++) {
        result[i] = (one_minus_both[i] > min_floor[i]) ? one_minus_both[i] : min_floor[i];
    }
}
