/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_cvs_num_b_5fea0037.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_cvs_num_b_5fea0037.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.cvs_num_b_5fea0037
 * ORIGIN SYMBOL:    purce_test.cvs_num_b
 * ORIGIN FILE:      purce_test:583
 * ORIGIN SIGNATURE: float64 wl_sl -> float64 ws_ss -> float64
 *
 * MATH INTENT:
 *   Function 'cvs_num_b' composed of: element_add
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.add as element_add kernel (from: numpy.add)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_cvs_num_b_5fea0037(int n, const double * restrict wl_sl, const double * restrict ws_ss, double * restrict result) {
    /* Element-wise addition: result[i] = wl_sl[i] + ws_ss[i] */
    for (int i = 0; i < n; i++) {
        result[i] = wl_sl[i] + ws_ss[i];
    }
}
