/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_density_ratio_8e370f4d.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_density_ratio_8e370f4d.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.density_ratio_8e370f4d
 * ORIGIN SYMBOL:    purce_test.density_ratio
 * ORIGIN FILE:      purce_test:393
 * ORIGIN SIGNATURE: float64 rho_transit -> float64 rho_tic_max -> float64
 *
 * MATH INTENT:
 *   Function 'density_ratio' composed of: element_div
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.divide as element_div kernel (from: numpy.divide)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_density_ratio_8e370f4d(int n, const double * restrict rho_transit, const double * restrict rho_tic_max, double * restrict result) {
    /* Element-wise division: result[i] = rho_transit[i] / rho_tic_max[i] (IEEE 754: x/0 = +/-inf, 0/0 = NaN) */
    for (int i = 0; i < n; i++) {
        result[i] = rho_transit[i] / rho_tic_max[i];
    }
}
