/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_depths_chi2_reduced_7e1fb243.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_depths_chi2_reduced_7e1fb243.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.depths_chi2_reduced_7e1fb243
 * ORIGIN SYMBOL:    purce_test.depths_chi2_reduced
 * ORIGIN FILE:      purce_test:731
 * ORIGIN SIGNATURE: float64 ratio -> float64
 *
 * MATH INTENT:
 *   Function 'depths_chi2_reduced' composed of: reduce_mean
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.mean as reduce_mean kernel (from: numpy.mean)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_depths_chi2_reduced_7e1fb243(int n, const double * restrict ratio, double * restrict result) {
    /* Reduction mean: result = mean(ratio[0..n-1]) */
    double sum = 0.0;
    for (int i = 0; i < n; i++) {
        sum += ratio[i];
    }
    *result = (n > 0) ? (sum / (double)n) : 0.0;
}
