/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_geometry_ld_u2cen_term_1f85112d.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_geometry_ld_u2cen_term_1f85112d.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.geometry_ld_u2cen_term_1f85112d
 * ORIGIN SYMBOL:    purce_test.geometry_ld_u2cen_term
 * ORIGIN FILE:      purce_test:239
 * ORIGIN SIGNATURE: float64 u2 -> float64 zeropow_sq -> float64
 *
 * MATH INTENT:
 *   Function 'geometry_ld_u2cen_term' composed of: element_mul
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.multiply as element_mul kernel (from: numpy.multiply)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_geometry_ld_u2cen_term_1f85112d(int n, const double * restrict u2, const double * restrict zeropow_sq, double * restrict result) {
    /* Element-wise multiplication: result[i] = u2[i] * zeropow_sq[i] */
    for (int i = 0; i < n; i++) {
        result[i] = u2[i] * zeropow_sq[i];
    }
}
