/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_geometry_k_1e7eb8fa.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_geometry_k_1e7eb8fa.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.geometry_k_1e7eb8fa
 * ORIGIN SYMBOL:    purce_test.geometry_k
 * ORIGIN FILE:      purce_test:189
 * ORIGIN SIGNATURE: float64 delta_clamped -> float64
 *
 * MATH INTENT:
 *   Function 'geometry_k' composed of: element_sqrt
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.sqrt as element_sqrt kernel (from: numpy.sqrt)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_geometry_k_1e7eb8fa(int n, const double * restrict delta_clamped, double * restrict result) {
    /* Element-wise square root: result[i] = sqrt(delta_clamped[i]) */
    for (int i = 0; i < n; i++) {
        result[i] = sqrt(delta_clamped[i]);
    }
}
