/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_geometry_ld_numerator_c3bebab1.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_geometry_ld_numerator_c3bebab1.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.geometry_ld_numerator_c3bebab1
 * ORIGIN SYMBOL:    purce_test.geometry_ld_numerator
 * ORIGIN FILE:      purce_test:259
 * ORIGIN SIGNATURE: float64 k_sq -> float64 i_cen -> float64
 *
 * MATH INTENT:
 *   Function 'geometry_ld_numerator' composed of: element_mul
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.multiply as element_mul kernel (from: numpy.multiply)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_geometry_ld_numerator_c3bebab1(int n, const double * restrict k_sq, const double * restrict i_cen, double * restrict result) {
    /* Element-wise multiplication: result[i] = k_sq[i] * i_cen[i] */
    for (int i = 0; i < n; i++) {
        result[i] = k_sq[i] * i_cen[i];
    }
}
