/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_cvs_wl_sl_a06915c5.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_cvs_wl_sl_a06915c5.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.cvs_wl_sl_a06915c5
 * ORIGIN SYMBOL:    purce_test.cvs_wl_sl
 * ORIGIN FILE:      purce_test:568
 * ORIGIN SIGNATURE: float64 w_l -> float64 s_l -> float64
 *
 * MATH INTENT:
 *   Function 'cvs_wl_sl' composed of: element_mul
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.multiply as element_mul kernel (from: numpy.multiply)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_cvs_wl_sl_a06915c5(int n, const double * restrict w_l, const double * restrict s_l, double * restrict result) {
    /* Element-wise multiplication: result[i] = w_l[i] * s_l[i] */
    for (int i = 0; i < n; i++) {
        result[i] = w_l[i] * s_l[i];
    }
}
