/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_chi_diff_da096401.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_chi_diff_da096401.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.chi_diff_da096401
 * ORIGIN SYMBOL:    purce_test.chi_diff
 * ORIGIN FILE:      purce_test:622
 * ORIGIN SIGNATURE: float64 flux -> float64 model_flux -> float64
 *
 * MATH INTENT:
 *   Function 'chi_diff' composed of: element_sub
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.subtract as element_sub kernel (from: numpy.subtract)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_chi_diff_da096401(int n, const double * restrict flux, const double * restrict model_flux, double * restrict result) {
    /* Element-wise subtraction: result[i] = flux[i] - model_flux[i] */
    for (int i = 0; i < n; i++) {
        result[i] = flux[i] - model_flux[i];
    }
}
