/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_probability_sin_arg_ba4c35df.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_probability_sin_arg_ba4c35df.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.probability_sin_arg_ba4c35df
 * ORIGIN SYMBOL:    purce_test.probability_sin_arg
 * ORIGIN FILE:      purce_test:477
 * ORIGIN SIGNATURE: float64 sin_prod -> float64 pi -> float64
 *
 * MATH INTENT:
 *   Function 'probability_sin_arg' composed of: element_min
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.minimum as element_min kernel (from: numpy.minimum)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_probability_sin_arg_ba4c35df(int n, const double * restrict sin_prod, const double * restrict pi, double * restrict result) {
    /* Element-wise minimum: result[i] = min(sin_prod[i], pi[i]) */
    for (int i = 0; i < n; i++) {
        result[i] = (sin_prod[i] < pi[i]) ? sin_prod[i] : pi[i];
    }
}
