/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_geometry_ld_cen_sub_cb912ca8.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_geometry_ld_cen_sub_cb912ca8.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.geometry_ld_cen_sub_cb912ca8
 * ORIGIN SYMBOL:    purce_test.geometry_ld_cen_sub
 * ORIGIN FILE:      purce_test:244
 * ORIGIN SIGNATURE: float64 one -> float64 u1cen_term -> float64
 *
 * MATH INTENT:
 *   Function 'geometry_ld_cen_sub' composed of: element_sub
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.subtract as element_sub kernel (from: numpy.subtract)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_geometry_ld_cen_sub_cb912ca8(int n, const double * restrict one, const double * restrict u1cen_term, double * restrict result) {
    /* Element-wise subtraction: result[i] = one[i] - u1cen_term[i] */
    for (int i = 0; i < n; i++) {
        result[i] = one[i] - u1cen_term[i];
    }
}
