/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_probability_b_clamped_2d63b1a5.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_probability_b_clamped_2d63b1a5.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.probability_b_clamped_2d63b1a5
 * ORIGIN SYMBOL:    purce_test.probability_b_clamped
 * ORIGIN FILE:      purce_test:512
 * ORIGIN SIGNATURE: float64 b_sq -> float64 _const_0 -> float64
 *
 * MATH INTENT:
 *   Function 'probability_b_clamped' composed of: element_max
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.maximum as element_max kernel (from: numpy.maximum)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_probability_b_clamped_2d63b1a5(int n, const double * restrict b_sq, double * restrict result) {
    /* Element-wise maximum: result[i] = max(b_sq[i], 0.0) */
    for (int i = 0; i < n; i++) {
        result[i] = (b_sq[i] > 0.0) ? b_sq[i] : 0.0;
    }
}
