/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_cvs_num_a_0ef3179d.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_cvs_num_a_0ef3179d.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.cvs_num_a_0ef3179d
 * ORIGIN SYMBOL:    purce_test.cvs_num_a
 * ORIGIN FILE:      purce_test:578
 * ORIGIN SIGNATURE: float64 wp_sp -> float64 wd_sd -> float64
 *
 * MATH INTENT:
 *   Function 'cvs_num_a' composed of: element_add
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.add as element_add kernel (from: numpy.add)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_cvs_num_a_0ef3179d(int n, const double * restrict wp_sp, const double * restrict wd_sd, double * restrict result) {
    /* Element-wise addition: result[i] = wp_sp[i] + wd_sd[i] */
    for (int i = 0; i < n; i++) {
        result[i] = wp_sp[i] + wd_sd[i];
    }
}
