/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_kepler_a3_num_6b05fb25.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_kepler_a3_num_6b05fb25.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.kepler_a3_num_6b05fb25
 * ORIGIN SYMBOL:    purce_test.kepler_a3_num
 * ORIGIN FILE:      purce_test:54
 * ORIGIN SIGNATURE: float64 gm -> float64 p_sec_sq -> float64
 *
 * MATH INTENT:
 *   Function 'kepler_a3_num' composed of: element_mul
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.multiply as element_mul kernel (from: numpy.multiply)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_kepler_a3_num_6b05fb25(int n, const double * restrict gm, const double * restrict p_sec_sq, double * restrict result) {
    /* Element-wise multiplication: result[i] = gm[i] * p_sec_sq[i] */
    for (int i = 0; i < n; i++) {
        result[i] = gm[i] * p_sec_sq[i];
    }
}
