/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_geometry_ld_corrected_2932f564.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_geometry_ld_corrected_2932f564.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.geometry_ld_corrected_2932f564
 * ORIGIN SYMBOL:    purce_test.geometry_ld_corrected
 * ORIGIN FILE:      purce_test:264
 * ORIGIN SIGNATURE: float64 numerator -> float64 i_mean -> float64
 *
 * MATH INTENT:
 *   Function 'geometry_ld_corrected' composed of: element_div
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.divide as element_div kernel (from: numpy.divide)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_geometry_ld_corrected_2932f564(int n, const double * restrict numerator, const double * restrict i_mean, double * restrict result) {
    /* Element-wise division: result[i] = numerator[i] / i_mean[i] (IEEE 754: x/0 = +/-inf, 0/0 = NaN) */
    for (int i = 0; i < n; i++) {
        result[i] = numerator[i] / i_mean[i];
    }
}
