/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_cvs_den_b_d80e7ea7.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_cvs_den_b_d80e7ea7.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.cvs_den_b_d80e7ea7
 * ORIGIN SYMBOL:    purce_test.cvs_den_b
 * ORIGIN FILE:      purce_test:598
 * ORIGIN SIGNATURE: float64 w_l -> float64 w_s -> float64
 *
 * MATH INTENT:
 *   Function 'cvs_den_b' composed of: element_add
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.add as element_add kernel (from: numpy.add)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_cvs_den_b_d80e7ea7(int n, const double * restrict w_l, const double * restrict w_s, double * restrict result) {
    /* Element-wise addition: result[i] = w_l[i] + w_s[i] */
    for (int i = 0; i < n; i++) {
        result[i] = w_l[i] + w_s[i];
    }
}
