/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_density_vol_8b2d0de9.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_density_vol_8b2d0de9.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.density_vol_8b2d0de9
 * ORIGIN SYMBOL:    purce_test.density_vol
 * ORIGIN FILE:      purce_test:373
 * ORIGIN SIGNATURE: float64 vol_coeff -> float64 R_star_cubed -> float64
 *
 * MATH INTENT:
 *   Function 'density_vol' composed of: element_mul
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.multiply as element_mul kernel (from: numpy.multiply)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_density_vol_8b2d0de9(int n, const double * restrict vol_coeff, const double * restrict R_star_cubed, double * restrict result) {
    /* Element-wise multiplication: result[i] = vol_coeff[i] * R_star_cubed[i] */
    for (int i = 0; i < n; i++) {
        result[i] = vol_coeff[i] * R_star_cubed[i];
    }
}
