/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_probability_sin_term_7c12001e.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_probability_sin_term_7c12001e.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.probability_sin_term_7c12001e
 * ORIGIN SYMBOL:    purce_test.probability_sin_term
 * ORIGIN FILE:      purce_test:487
 * ORIGIN SIGNATURE: float64 a_over_rs -> float64 sin_val -> float64
 *
 * MATH INTENT:
 *   Function 'probability_sin_term' composed of: element_mul
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.multiply as element_mul kernel (from: numpy.multiply)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_probability_sin_term_7c12001e(int n, const double * restrict a_over_rs, const double * restrict sin_val, double * restrict result) {
    /* Element-wise multiplication: result[i] = a_over_rs[i] * sin_val[i] */
    for (int i = 0; i < n; i++) {
        result[i] = a_over_rs[i] * sin_val[i];
    }
}
