/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_probability_cos_clamped_1de9bfa6.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_probability_cos_clamped_1de9bfa6.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.probability_cos_clamped_1de9bfa6
 * ORIGIN SYMBOL:    purce_test.probability_cos_clamped
 * ORIGIN FILE:      purce_test:542
 * ORIGIN SIGNATURE: float64 cos_max -> float64 one -> float64
 *
 * MATH INTENT:
 *   Function 'probability_cos_clamped' composed of: element_min
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.minimum as element_min kernel (from: numpy.minimum)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_probability_cos_clamped_1de9bfa6(int n, const double * restrict cos_max, const double * restrict one, double * restrict result) {
    /* Element-wise minimum: result[i] = min(cos_max[i], one[i]) */
    for (int i = 0; i < n; i++) {
        result[i] = (cos_max[i] < one[i]) ? cos_max[i] : one[i];
    }
}
