/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_geometry_rp_m_2a415928.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_geometry_rp_m_2a415928.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.geometry_rp_m_2a415928
 * ORIGIN SYMBOL:    purce_test.geometry_rp_m
 * ORIGIN FILE:      purce_test:294
 * ORIGIN SIGNATURE: float64 k -> float64 R_star -> float64
 *
 * MATH INTENT:
 *   Function 'geometry_rp_m' composed of: element_mul
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.multiply as element_mul kernel (from: numpy.multiply)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_geometry_rp_m_2a415928(int n, const double * restrict k, const double * restrict R_star, double * restrict result) {
    /* Element-wise multiplication: result[i] = k[i] * R_star[i] */
    for (int i = 0; i < n; i++) {
        result[i] = k[i] * R_star[i];
    }
}
