/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_geometry_ld_zeropow_02562496.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_geometry_ld_zeropow_02562496.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.geometry_ld_zeropow_02562496
 * ORIGIN SYMBOL:    purce_test.geometry_ld_zeropow
 * ORIGIN FILE:      purce_test:229
 * ORIGIN SIGNATURE: float64 zeropow_diff -> float64 exponent -> float64
 *
 * MATH INTENT:
 *   Function 'geometry_ld_zeropow' composed of: element_power
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.power as element_power kernel (from: numpy.power)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_geometry_ld_zeropow_02562496(int n, const double * restrict zeropow_diff, const double * restrict exponent, double * restrict result) {
    /* Element-wise power: result[i] = pow(zeropow_diff[i], exponent[i]) */
    for (int i = 0; i < n; i++) {
        result[i] = pow(zeropow_diff[i], exponent[i]);
    }
}
