/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_welch_se_o_sq_7b6bf9ac.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_welch_se_o_sq_7b6bf9ac.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.welch_se_o_sq_7b6bf9ac
 * ORIGIN SYMBOL:    purce_test.welch_se_o_sq
 * ORIGIN FILE:      purce_test:790
 * ORIGIN SIGNATURE: float64 se_o -> float64 _const_0 -> float64
 *
 * MATH INTENT:
 *   Function 'welch_se_o_sq' composed of: element_power
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.power as element_power kernel (from: numpy.power)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_welch_se_o_sq_7b6bf9ac(int n, const double * restrict se_o, double * restrict result) {
    /* Element-wise power: result[i] = pow(se_o[i], 2.0) */
    for (int i = 0; i < n; i++) {
        result[i] = pow(se_o[i], 2.0);
    }
}
