/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_kepler_gm_full_18822df0.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_kepler_gm_full_18822df0.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.kepler_gm_full_18822df0
 * ORIGIN SYMBOL:    purce_test.kepler_gm_full
 * ORIGIN FILE:      purce_test:44
 * ORIGIN SIGNATURE: float64 gm_partial -> float64 m_sun -> float64
 *
 * MATH INTENT:
 *   Function 'kepler_gm_full' composed of: element_mul
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.multiply as element_mul kernel (from: numpy.multiply)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_kepler_gm_full_18822df0(int n, const double * restrict gm_partial, const double * restrict m_sun, double * restrict result) {
    /* Element-wise multiplication: result[i] = gm_partial[i] * m_sun[i] */
    for (int i = 0; i < n; i++) {
        result[i] = gm_partial[i] * m_sun[i];
    }
}
