/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_probability_sin_b4a651a3.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_probability_sin_b4a651a3.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.probability_sin_b4a651a3
 * ORIGIN SYMBOL:    purce_test.probability_sin
 * ORIGIN FILE:      purce_test:482
 * ORIGIN SIGNATURE: float64 sin_arg -> float64
 *
 * MATH INTENT:
 *   Function 'probability_sin' composed of: element_sin
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.sin as element_sin kernel (from: numpy.sin)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_probability_sin_b4a651a3(int n, const double * restrict sin_arg, double * restrict result) {
    /* Element-wise sine: result[i] = sin(sin_arg[i]) */
    for (int i = 0; i < n; i++) {
        result[i] = sin(sin_arg[i]);
    }
}
