/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_kepler_a_m_0a4ce779.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_kepler_a_m_0a4ce779.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.kepler_a_m_0a4ce779
 * ORIGIN SYMBOL:    purce_test.kepler_a_m
 * ORIGIN FILE:      purce_test:74
 * ORIGIN SIGNATURE: float64 a3 -> float64 inv3 -> float64
 *
 * MATH INTENT:
 *   Function 'kepler_a_m' composed of: element_power
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.power as element_power kernel (from: numpy.power)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_kepler_a_m_0a4ce779(int n, const double * restrict a3, const double * restrict inv3, double * restrict result) {
    /* Element-wise power: result[i] = pow(a3[i], inv3[i]) */
    for (int i = 0; i < n; i++) {
        result[i] = pow(a3[i], inv3[i]);
    }
}
