/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_geometry_u1_term_ff9ceb83.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_geometry_u1_term_ff9ceb83.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.geometry_u1_term_ff9ceb83
 * ORIGIN SYMBOL:    purce_test.geometry_u1_term
 * ORIGIN FILE:      purce_test:199
 * ORIGIN SIGNATURE: float64 u1 -> float64 inv3 -> float64
 *
 * MATH INTENT:
 *   Function 'geometry_u1_term' composed of: element_mul
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.multiply as element_mul kernel (from: numpy.multiply)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_geometry_u1_term_ff9ceb83(int n, const double * restrict u1, const double * restrict inv3, double * restrict result) {
    /* Element-wise multiplication: result[i] = u1[i] * inv3[i] */
    for (int i = 0; i < n; i++) {
        result[i] = u1[i] * inv3[i];
    }
}
