/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_geometry_cons_resid_sub_c41f4765.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_geometry_cons_resid_sub_c41f4765.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.geometry_cons_resid_sub_c41f4765
 * ORIGIN SYMBOL:    purce_test.geometry_cons_resid_sub
 * ORIGIN FILE:      purce_test:269
 * ORIGIN SIGNATURE: float64 delta -> float64 k_sq -> float64
 *
 * MATH INTENT:
 *   Function 'geometry_cons_resid_sub' composed of: element_sub
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.subtract as element_sub kernel (from: numpy.subtract)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_geometry_cons_resid_sub_c41f4765(int n, const double * restrict delta, const double * restrict k_sq, double * restrict result) {
    /* Element-wise subtraction: result[i] = delta[i] - k_sq[i] */
    for (int i = 0; i < n; i++) {
        result[i] = delta[i] - k_sq[i];
    }
}
