/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT — HEADER
 * GENERATED FILE:   purce_test.h
 * SOURCE MODULE:    purce_test
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 * ═══════════════════════════════════════════════════════════════════════════ */

#ifndef PURCE_TEST_H
#define PURCE_TEST_H

#include <stdint.h>
#include <math.h>

void purce_test_density_vol_8b2d0de9(int n, const double * restrict vol_coeff, const double * restrict R_star_cubed, double * restrict result);

void purce_test_geometry_ld_zeropow_diff_d7a5a23a(int n, const double * restrict one, const double * restrict mu_c, double * restrict result);

void purce_test_density_rho_transit_gcc_f1030a49(int n, const double * restrict rho_kgm3, const double * restrict inv1000, double * restrict result);

void purce_test_density_rho_pow_a_74b9e516(int n, const double * restrict a_over_rs, const double * restrict three, double * restrict result);

void purce_test_cvs_ws_ss_de914cd1(int n, const double * restrict w_s, const double * restrict s_s, double * restrict result);

void purce_test_density_g_num_625ba494(int n, const double * restrict G, const double * restrict M_star, double * restrict result);

void purce_test_geometry_u2_term_be22225e(int n, const double * restrict u2, const double * restrict inv6, double * restrict result);

void purce_test_depth_cons_sub_57ebf000(int n, const double * restrict one, const double * restrict ratio, double * restrict result);

void purce_test_depth_cons_ratio_a638f61f(int n, const double * restrict chi_sub, const double * restrict norm_sub, double * restrict result);

void purce_test_chi_resid_sq_677381e0(int n, const double * restrict residuals, double _const_0, double * restrict result);

void purce_test_kepler_a3_5862e673(int n, const double * restrict a3_num, const double * restrict denom, double * restrict result);

void purce_test_kepler_expect_max_76ca4c8d(int n, const double * restrict expect, const double * restrict eps, double * restrict result);

void purce_test_kepler_ratio_si_527d13ed(int n, const double * restrict p_sec_sq, const double * restrict a_m_cubed, double * restrict result);

void purce_test_probability_sin_b4a651a3(int n, const double * restrict sin_arg, double * restrict result);

void purce_test_kepler_diff_si_4d4783ca(int n, const double * restrict ratio_si, const double * restrict expected_si, double * restrict result);

void purce_test_kepler_pi_sq_857071e2(int n, const double * restrict pi, double _const_0, double * restrict result);

void purce_test_geometry_cons_resid_abs_ada5525d(int n, const double * restrict sub, double * restrict result);

void purce_test_density_g_cgs_max_75717ee1(int n, const double * restrict g_cgs, const double * restrict one, double * restrict result);

void purce_test_cvs_score_a75a30c1(int n, const double * restrict numerator, const double * restrict total_max, double * restrict result);

void purce_test_geometry_cons_resid_pct_abd2b692(int n, const double * restrict residual, const double * restrict hundred, double * restrict result);

void purce_test_density_a_over_rs_num_e28e6d77(int n, const double * restrict P_sec, const double * restrict one_plus_k, double * restrict result);

void purce_test_cvs_wp_sp_0116f948(int n, const double * restrict w_p, const double * restrict s_p, double * restrict result);

void purce_test_depths_cv_c31eac56(int n, const double * restrict std, const double * restrict mu_max, double * restrict result);

void purce_test_cvs_den_b_d80e7ea7(int n, const double * restrict w_l, const double * restrict w_s, double * restrict result);

void purce_test_probability_b_sq_cb568370(int n, const double * restrict opk_sq, const double * restrict st_sq, double * restrict result);

void purce_test_kepler_diff_solar_abs_f6d10dab(int n, const double * restrict diff, double * restrict result);

void purce_test_welch_den_max_6695161f(int n, const double * restrict den_sqrt, const double * restrict eps, double * restrict result);

void purce_test_chi_dof_0ac82e16(int n, const double * restrict n_minus, const double * restrict one, double * restrict result);

void purce_test_kepler_expect_solar_f6e79e37(int n, const double * restrict one, const double * restrict M_star_solar, double * restrict result);

void purce_test_geometry_ld_i_mean_8efa5ea4(int n, const double * restrict one_minus_both, const double * restrict min_floor, double * restrict result);

void purce_test_density_logg_8fde41c0(int n, const double * restrict g_cgs_max, double * restrict result);

void purce_test_probability_sin_term_7c12001e(int n, const double * restrict a_over_rs, const double * restrict sin_val, double * restrict result);

void purce_test_depths_err_sq_ef7a5db2(int n, const double * restrict errs, double _const_0, double * restrict result);

void purce_test_density_g_cgs_div_06d04c02(int n, const double * restrict g_num, const double * restrict g_den, double * restrict result);

void purce_test_density_g_cgs_0f1cae1c(int n, const double * restrict g_cgs_div, const double * restrict hundred, double * restrict result);

void purce_test_probability_st_sq_8b93b723(int n, const double * restrict sin_term, double _const_0, double * restrict result);

void purce_test_density_rho_den_33e7839f(int n, const double * restrict G, const double * restrict p_sec_sq, double * restrict result);

void purce_test_density_rho_tic_gcc_44b154cc(int n, const double * restrict rho_kgm3, const double * restrict inv1000, double * restrict result);

void purce_test_cvs_numerator_2ab47413(int n, const double * restrict num_a, const double * restrict num_b, double * restrict result);

void purce_test_chi_reduced_alt_eda35819(int n, const double * restrict chi2, const double * restrict dof, double * restrict result);

void purce_test_kepler_a_au_bbb464eb(int n, const double * restrict a_m, const double * restrict au, double * restrict result);

void purce_test_probability_a_over_rs_9787b09a(int n, const double * restrict a_m, const double * restrict rstar_max, double * restrict result);

void purce_test_probability_ptr_clamped_24b013a4(int n, const double * restrict ptr, const double * restrict one, double * restrict result);

void purce_test_probability_ingress_ratio_16bc4af7(int n, const double * restrict k, const double * restrict den, double * restrict result);

void purce_test_chi_squared_688c91db(int n, const double * restrict resid_sq, double * restrict result);

void purce_test_kepler_expected_si_3c1bfc3c(int n, const double * restrict four_pi_sq, const double * restrict gm, double * restrict result);

void purce_test_density_tdur_max_9e7423f6(int n, const double * restrict T_sec, const double * restrict one, double * restrict result);

void purce_test_geometry_rp_m_2a415928(int n, const double * restrict k, const double * restrict R_star, double * restrict result);

void purce_test_chi_alt_dof_max_c8f6720b(int n, const double * restrict dof, const double * restrict one, double * restrict result);

void purce_test_depths_std_sqrt_149dc9d5(int n, const double * restrict sample_var, double * restrict result);

void purce_test_kepler_diff_solar_5ffb7559(int n, const double * restrict ratio, const double * restrict expect, double * restrict result);

void purce_test_geometry_ld_corrected_2932f564(int n, const double * restrict numerator, const double * restrict i_mean, double * restrict result);

void purce_test_depths_mu_max_afc77201(int n, const double * restrict mu, const double * restrict eps, double * restrict result);

void purce_test_kepler_a_au_cubed_ff168c58(int n, const double * restrict a_au, double _const_0, double * restrict result);

void purce_test_depths_var_pop_4b1fb4b9(int n, const double * restrict depths, double * restrict result);

void purce_test_chi_n_minus_889c185a(int n_len, const double * restrict n, const double * restrict one, double * restrict result);

void purce_test_kepler_p_sec_sq_2_52cd457d(int n, const double * restrict P_sec, double _const_0, double * restrict result);

void purce_test_depth_cons_chi_sub_292b7f19(int n, const double * restrict chi2_red, const double * restrict one, double * restrict result);

void purce_test_depths_resid_1cc49286(int n, const double * restrict depths, const double * restrict mu, double * restrict result);

void purce_test_geometry_ld_i_cen_699d12ac(int n, const double * restrict one_minus_both, const double * restrict min_floor, double * restrict result);

void purce_test_density_vol_coeff_2e8eb5d5(int n, const double * restrict four_thirds, const double * restrict pi, double * restrict result);

void purce_test_geometry_k_1e7eb8fa(int n, const double * restrict delta_clamped, double * restrict result);

void purce_test_geometry_cons_resid_div_27de7eeb(int n, const double * restrict diff_abs, const double * restrict k_sq_max, double * restrict result);

void purce_test_geometry_cons_k_sq_max_22b169b0(int n, const double * restrict k_sq, const double * restrict eps, double * restrict result);

void purce_test_cvs_num_b_5fea0037(int n, const double * restrict wl_sl, const double * restrict ws_ss, double * restrict result);

void purce_test_probability_sin_ratio_92faaf44(int n, const double * restrict T_sec, const double * restrict p_max, double * restrict result);

void purce_test_depths_resid_sq_3d829989(int n, const double * restrict resid, double _const_0, double * restrict result);

void purce_test_probability_p_max_bf57245f(int n, const double * restrict P_sec, const double * restrict one, double * restrict result);

void purce_test_probability_opk_sq_a2ed6acd(int n, const double * restrict one_plus_k, double _const_0, double * restrict result);

void purce_test_depths_mean_b194ed13(int n, const double * restrict depths, double * restrict result);

void purce_test_welch_se_o_sq_7b6bf9ac(int n, const double * restrict se_o, double _const_0, double * restrict result);

void purce_test_density_rho_tic_max_8fdab8df(int n, const double * restrict rho_tic, const double * restrict eps, double * restrict result);

void purce_test_welch_delta_sigma_83b6f10c(int n, const double * restrict delta_abs, const double * restrict den_max, double * restrict result);

void purce_test_probability_ptr_725f8a1b(int n, const double * restrict num, const double * restrict den, double * restrict result);

void purce_test_kepler_residual_solar_3f98bb0f(int n, const double * restrict norm_diff, const double * restrict hundred, double * restrict result);

void purce_test_probability_sin_prod_05eb950b(int n, const double * restrict pi, const double * restrict ratio, double * restrict result);

void purce_test_probability_ingress_hrs_05c003bf(int n, const double * restrict T_hrs, const double * restrict ratio, double * restrict result);

void purce_test_cvs_num_a_0ef3179d(int n, const double * restrict wp_sp, const double * restrict wd_sd, double * restrict result);

void purce_test_kepler_denominator_4590064a(int n, const double * restrict four, const double * restrict pi_sq, double * restrict result);

void purce_test_density_g_den_c9dfe5d9(int n, const double * restrict R_star, double _const_0, double * restrict result);

void purce_test_kepler_gm_full_18822df0(int n, const double * restrict gm_partial, const double * restrict m_sun, double * restrict result);

void purce_test_geometry_ld_cen_sub2_58bc760c(int n, const double * restrict one_minus_u1, const double * restrict u2cen_term, double * restrict result);

void purce_test_welch_sqrt_n_e1429177(int n_len, const double * restrict n, double * restrict result);

void purce_test_geometry_delta_clamped_bea85157(int n, const double * restrict delta, const double * restrict eps, double * restrict result);

void purce_test_kepler_a_m_cubed_1e481c71(int n, const double * restrict a_m, double _const_0, double * restrict result);

void purce_test_kepler_p_sec_sq_3c3ca8a8(int n, const double * restrict P_sec, double _const_0, double * restrict result);

void purce_test_welch_se_e_sq_961181a8(int n, const double * restrict se_e, double _const_0, double * restrict result);

void purce_test_density_rho_transit_kgm3_7f726358(int n, const double * restrict coeff, const double * restrict rho_pow, double * restrict result);

void purce_test_chi_reduced_71eb947f(int n, const double * restrict chi2, const double * restrict dof, double * restrict result);

void purce_test_kepler_diff_abs_64d34688(int n, const double * restrict diff, double * restrict result);

void purce_test_welch_var_sum_626abb29(int n, const double * restrict se_e_sq, const double * restrict se_o_sq, double * restrict result);

void purce_test_probability_cos_max_09b58d83(int n, const double * restrict num, const double * restrict a_m, double * restrict result);

void purce_test_density_ratio_8e370f4d(int n, const double * restrict rho_transit, const double * restrict rho_tic_max, double * restrict result);

void purce_test_geometry_ld_u2cen_term_1f85112d(int n, const double * restrict u2, const double * restrict zeropow_sq, double * restrict result);

void purce_test_welch_se_b7dc9429(int n, const double * restrict sigma, const double * restrict sqrt_n, double * restrict result);

void purce_test_density_vol_pow_d4475916(int n, const double * restrict R_star, double _const_0, double * restrict result);

void purce_test_welch_delta_cb20ee08(int n, const double * restrict mu_e, const double * restrict mu_o, double * restrict result);

void purce_test_chi_residuals_f773d43f(int n, const double * restrict diff, const double * restrict flux_err, double * restrict result);

void purce_test_depths_std_scale_7adde1ef(int n_len, const double * restrict var, const double * restrict n, double * restrict result);

void purce_test_kepler_norm_solar_db4293c1(int n, const double * restrict diff_abs, const double * restrict expect_max, double * restrict result);

void purce_test_depths_chi2_reduced_7e1fb243(int n, const double * restrict ratio, double * restrict result);

void purce_test_cvs_den_a_0fd02983(int n, const double * restrict w_p, const double * restrict w_d, double * restrict result);

void purce_test_density_rho_coeff_60babfe0(int n, const double * restrict three_pi, const double * restrict rho_den, double * restrict result);

void purce_test_depth_cons_norm_sub_f903e415(int n, const double * restrict norm, const double * restrict one, double * restrict result);

void purce_test_geometry_ld_sub2_8cc9b7e2(int n, const double * restrict one_minus_u1, const double * restrict u2_term, double * restrict result);

void purce_test_density_one_plus_k_bc0f77c4(int n, const double * restrict k, const double * restrict one, double * restrict result);

void purce_test_density_rho_pow_p_0362c723(int n, const double * restrict P_sec, double _const_0, double * restrict result);

void purce_test_welch_den_sqrt_dacf6499(int n, const double * restrict var_sum, double * restrict result);

void purce_test_probability_sin_arg_ba4c35df(int n, const double * restrict sin_prod, const double * restrict pi, double * restrict result);

void purce_test_probability_rstar_max_3c5f0e76(int n, const double * restrict R_star, const double * restrict eps, double * restrict result);

void purce_test_probability_b_clamped_2d63b1a5(int n, const double * restrict b_sq, double _const_0, double * restrict result);

void purce_test_kepler_ratio_solar_412e3aff(int n, const double * restrict p_yr_sq, const double * restrict a_au_max, double * restrict result);

void purce_test_geometry_cons_resid_sub_c41f4765(int n, const double * restrict delta, const double * restrict k_sq, double * restrict result);

void purce_test_probability_num_3c729ce1(int n, const double * restrict R_star, const double * restrict R_planet, double * restrict result);

void purce_test_probability_den_25d25124(int n, const double * restrict a_m, const double * restrict num, double * restrict result);

void purce_test_cvs_wd_sd_2385fe3a(int n, const double * restrict w_d, const double * restrict s_d, double * restrict result);

void purce_test_chi_alt_dof_204ac30b(int n_len, const double * restrict n, const double * restrict n_params, double * restrict result);

void purce_test_probability_cos_clamped_1de9bfa6(int n, const double * restrict cos_max, const double * restrict one, double * restrict result);

void purce_test_cvs_total_max_cfd98b83(int n, const double * restrict total, const double * restrict eps, double * restrict result);

void purce_test_geometry_u1_term_ff9ceb83(int n, const double * restrict u1, const double * restrict inv3, double * restrict result);

void purce_test_depths_std_scale2_2124da6a(int n, const double * restrict scaled, const double * restrict inv_nm1, double * restrict result);

void purce_test_geometry_ld_u1cen_term_145d8e8d(int n, const double * restrict u1, const double * restrict zeropow, double * restrict result);

void purce_test_kepler_residual_si_97f8d83f(int n, const double * restrict norm_diff, const double * restrict hundred, double * restrict result);

void purce_test_cvs_wl_sl_a06915c5(int n, const double * restrict w_l, const double * restrict s_l, double * restrict result);

void purce_test_chi_diff_da096401(int n, const double * restrict flux, const double * restrict model_flux, double * restrict result);

void purce_test_kepler_a_m_0a4ce779(int n, const double * restrict a3, const double * restrict inv3, double * restrict result);

void purce_test_kepler_gm_f676df7d(int n, const double * restrict G, const double * restrict M_star_solar, double * restrict result);

void purce_test_geometry_ld_cen_sub_cb912ca8(int n, const double * restrict one, const double * restrict u1cen_term, double * restrict result);

void purce_test_density_rho_tic_kgm3_89c5ff7f(int n, const double * restrict M_star, const double * restrict vol, double * restrict result);

void purce_test_geometry_ld_zeropow_02562496(int n, const double * restrict zeropow_diff, const double * restrict exponent, double * restrict result);

void purce_test_probability_ingress_den_0a49c5e6(int n, const double * restrict one_plus_k, const double * restrict eps, double * restrict result);

void purce_test_geometry_rp_earth_026d7fc2(int n, const double * restrict rp_m, const double * restrict r_earth, double * restrict result);

void purce_test_kepler_p_yr_sq_9a8b83f6(int n, const double * restrict P_yr, double _const_0, double * restrict result);

void purce_test_kepler_p_yr_871d0710(int n, const double * restrict P_days, const double * restrict inv365, double * restrict result);

void purce_test_probability_b_0a45d21f(int n, const double * restrict b_clamped, double * restrict result);

void purce_test_depth_consistency_s_5acee7ef(int n, const double * restrict sub, const double * restrict zero, const double * restrict one, double * restrict result);

void purce_test_geometry_ld_sub_3b1296dd(int n, const double * restrict one, const double * restrict u1_term, double * restrict result);

void purce_test_cvs_total_a3d1a36e(int n, const double * restrict den_a, const double * restrict den_b, double * restrict result);

void purce_test_geometry_ld_numerator_c3bebab1(int n, const double * restrict k_sq, const double * restrict i_cen, double * restrict result);

void purce_test_kepler_norm_diff_si_41ba5d1c(int n, const double * restrict diff_abs, const double * restrict expected_si, double * restrict result);

void purce_test_depths_ratio_b076a040(int n, const double * restrict resid_sq, const double * restrict err_sq, double * restrict result);

void purce_test_density_a_over_rs_den_d6501530(int n, const double * restrict pi, const double * restrict tdur_max, double * restrict result);

void purce_test_kepler_a_au_max_b35e6fe1(int n, const double * restrict a_au_cubed, const double * restrict eps, double * restrict result);

void purce_test_kepler_a3_num_6b05fb25(int n, const double * restrict gm, const double * restrict p_sec_sq, double * restrict result);

void purce_test_geometry_k_sq_d12576dd(int n, const double * restrict k, double _const_0, double * restrict result);

void purce_test_density_a_over_rs_transit_5eec6bb9(int n, const double * restrict num, const double * restrict den, double * restrict result);

void purce_test_probability_one_plus_k_f3dacaed(int n, const double * restrict k, const double * restrict one, double * restrict result);

void purce_test_welch_delta_abs_f735fe02(int n, const double * restrict delta, double * restrict result);

#endif /* PURCE_TEST_H */
