/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_density_one_plus_k_bc0f77c4.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_density_one_plus_k_bc0f77c4.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.density_one_plus_k_bc0f77c4
 * ORIGIN SYMBOL:    purce_test.density_one_plus_k
 * ORIGIN FILE:      purce_test:308
 * ORIGIN SIGNATURE: float64 k -> float64 one -> float64
 *
 * MATH INTENT:
 *   Function 'density_one_plus_k' composed of: element_add
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.add as element_add kernel (from: numpy.add)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_density_one_plus_k_bc0f77c4(int n, const double * restrict k, const double * restrict one, double * restrict result) {
    /* Element-wise addition: result[i] = k[i] + one[i] */
    for (int i = 0; i < n; i++) {
        result[i] = k[i] + one[i];
    }
}
