/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_geometry_ld_sub2_8cc9b7e2.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_geometry_ld_sub2_8cc9b7e2.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.geometry_ld_sub2_8cc9b7e2
 * ORIGIN SYMBOL:    purce_test.geometry_ld_sub2
 * ORIGIN FILE:      purce_test:214
 * ORIGIN SIGNATURE: float64 one_minus_u1 -> float64 u2_term -> float64
 *
 * MATH INTENT:
 *   Function 'geometry_ld_sub2' composed of: element_sub
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.subtract as element_sub kernel (from: numpy.subtract)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_geometry_ld_sub2_8cc9b7e2(int n, const double * restrict one_minus_u1, const double * restrict u2_term, double * restrict result) {
    /* Element-wise subtraction: result[i] = one_minus_u1[i] - u2_term[i] */
    for (int i = 0; i < n; i++) {
        result[i] = one_minus_u1[i] - u2_term[i];
    }
}
