/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_cvs_wd_sd_2385fe3a.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_cvs_wd_sd_2385fe3a.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.cvs_wd_sd_2385fe3a
 * ORIGIN SYMBOL:    purce_test.cvs_wd_sd
 * ORIGIN FILE:      purce_test:563
 * ORIGIN SIGNATURE: float64 w_d -> float64 s_d -> float64
 *
 * MATH INTENT:
 *   Function 'cvs_wd_sd' composed of: element_mul
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.multiply as element_mul kernel (from: numpy.multiply)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_cvs_wd_sd_2385fe3a(int n, const double * restrict w_d, const double * restrict s_d, double * restrict result) {
    /* Element-wise multiplication: result[i] = w_d[i] * s_d[i] */
    for (int i = 0; i < n; i++) {
        result[i] = w_d[i] * s_d[i];
    }
}
