/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_probability_rstar_max_3c5f0e76.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_probability_rstar_max_3c5f0e76.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.probability_rstar_max_3c5f0e76
 * ORIGIN SYMBOL:    purce_test.probability_rstar_max
 * ORIGIN FILE:      purce_test:452
 * ORIGIN SIGNATURE: float64 R_star -> float64 eps -> float64
 *
 * MATH INTENT:
 *   Function 'probability_rstar_max' composed of: element_max
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.maximum as element_max kernel (from: numpy.maximum)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_probability_rstar_max_3c5f0e76(int n, const double * restrict R_star, const double * restrict eps, double * restrict result) {
    /* Element-wise maximum: result[i] = max(R_star[i], eps[i]) */
    for (int i = 0; i < n; i++) {
        result[i] = (R_star[i] > eps[i]) ? R_star[i] : eps[i];
    }
}
