/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_density_rho_pow_a_74b9e516.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_density_rho_pow_a_74b9e516.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.density_rho_pow_a_74b9e516
 * ORIGIN SYMBOL:    purce_test.density_rho_pow_a
 * ORIGIN FILE:      purce_test:348
 * ORIGIN SIGNATURE: float64 a_over_rs -> float64 three -> float64
 *
 * MATH INTENT:
 *   Function 'density_rho_pow_a' composed of: element_power
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.power as element_power kernel (from: numpy.power)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_density_rho_pow_a_74b9e516(int n, const double * restrict a_over_rs, const double * restrict three, double * restrict result) {
    /* Element-wise power: result[i] = pow(a_over_rs[i], three[i]) */
    for (int i = 0; i < n; i++) {
        result[i] = pow(a_over_rs[i], three[i]);
    }
}
