/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_kepler_expect_solar_f6e79e37.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_kepler_expect_solar_f6e79e37.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.kepler_expect_solar_f6e79e37
 * ORIGIN SYMBOL:    purce_test.kepler_expect_solar
 * ORIGIN FILE:      purce_test:149
 * ORIGIN SIGNATURE: float64 one -> float64 M_star_solar -> float64
 *
 * MATH INTENT:
 *   Function 'kepler_expect_solar' composed of: element_div
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.divide as element_div kernel (from: numpy.divide)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_kepler_expect_solar_f6e79e37(int n, const double * restrict one, const double * restrict M_star_solar, double * restrict result) {
    /* Element-wise division: result[i] = one[i] / M_star_solar[i] (IEEE 754: x/0 = +/-inf, 0/0 = NaN) */
    for (int i = 0; i < n; i++) {
        result[i] = one[i] / M_star_solar[i];
    }
}
