/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_kepler_p_yr_871d0710.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_kepler_p_yr_871d0710.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.kepler_p_yr_871d0710
 * ORIGIN SYMBOL:    purce_test.kepler_p_yr
 * ORIGIN FILE:      purce_test:124
 * ORIGIN SIGNATURE: float64 P_days -> float64 inv365 -> float64
 *
 * MATH INTENT:
 *   Function 'kepler_p_yr' composed of: element_mul
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.multiply as element_mul kernel (from: numpy.multiply)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_kepler_p_yr_871d0710(int n, const double * restrict P_days, const double * restrict inv365, double * restrict result) {
    /* Element-wise multiplication: result[i] = P_days[i] * inv365[i] */
    for (int i = 0; i < n; i++) {
        result[i] = P_days[i] * inv365[i];
    }
}
