/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_probability_ingress_hrs_05c003bf.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_probability_ingress_hrs_05c003bf.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.probability_ingress_hrs_05c003bf
 * ORIGIN SYMBOL:    purce_test.probability_ingress_hrs
 * ORIGIN FILE:      purce_test:532
 * ORIGIN SIGNATURE: float64 T_hrs -> float64 ratio -> float64
 *
 * MATH INTENT:
 *   Function 'probability_ingress_hrs' composed of: element_mul
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.multiply as element_mul kernel (from: numpy.multiply)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_probability_ingress_hrs_05c003bf(int n, const double * restrict T_hrs, const double * restrict ratio, double * restrict result) {
    /* Element-wise multiplication: result[i] = T_hrs[i] * ratio[i] */
    for (int i = 0; i < n; i++) {
        result[i] = T_hrs[i] * ratio[i];
    }
}
