/* ═══════════════════════════════════════════════════════════════════════════
 * PURCE OUTPUT
 * GENERATED FILE:   purce_test_chi_alt_dof_204ac30b.c
 * SOURCE MODULE:    purce_test
 * SOURCE COMMIT:    unknown
 * GENERATED BY:     purce v0.1.0
 * GENERATED AT:     2026-08-17T23:06:53Z
 * TARGET PROFILE:   generic-c99
 *
 * PROVENANCE:       purce_test_chi_alt_dof_204ac30b.prov.json
 * ═══════════════════════════════════════════════════════════════════════════ */

#include <stdint.h>
#include <math.h>
#include <string.h>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* ───────────────────────────────────────────────────────────────────────────
 * SEMANTIC UNIT:    purce_test.chi_alt_dof_204ac30b
 * ORIGIN SYMBOL:    purce_test.chi_alt_dof
 * ORIGIN FILE:      purce_test:657
 * ORIGIN SIGNATURE: float64 n -> float64 n_params -> float64
 *
 * MATH INTENT:
 *   Function 'chi_alt_dof' composed of: element_sub
 *
 * REDUCTION LOG:
 *   [numpy_op_extraction] Extracted numpy.subtract as element_sub kernel (from: numpy.subtract)
 *
 * MEMORY CONTRACT:
 *   - Stack:   256 bytes
 *   - Heap:    NONE
 *   - Reentrancy: SAFE
 *
 * CORRECTNESS:
 *   - Verified: differential fuzzing (10k iterations)
 *   - Bounds:   within representable range for target dtype
 * ─────────────────────────────────────────────────────────────────────────── */

void purce_test_chi_alt_dof_204ac30b(int n_len, const double * restrict n, const double * restrict n_params, double * restrict result) {
    /* Element-wise subtraction: result[i] = n[i] - n_params[i] */
    for (int i = 0; i < n_len; i++) {
        result[i] = n[i] - n_params[i];
    }
}
