"""
verify_compare.py  ·  Differential verification: generated C kernels vs numpy
================================================================================
Computes reference values with numpy from purce_src/zspace_kernels.py using
the SAME deterministic inputs as tests/verify_kernels.c (generated by
gen_verify_kernels.py), then compares against the C output file.

Usage:
    python tests/verify_compare.py [path-to-c-output]
"""

import ast
import os
import re
import sys

import numpy as np

from gen_verify_kernels import NAMED, value_for

HERE = os.path.dirname(os.path.abspath(__file__))
SRC_PY = os.path.join(HERE, "..", "purce_src", "zspace_kernels.py")


def load_funcs():
    with open(SRC_PY, encoding="utf-8") as fh:
        tree = ast.parse(fh.read())
    ns = {}
    ns["np"] = np
    for node in tree.body:
        if isinstance(node, ast.FunctionDef):
            exec(compile(ast.Module(body=[node], type_ignores=[]), "<k>", "exec"), ns)
    return {f: ns[f] for f in ns if callable(ns[f])}


def main():
    funcs = load_funcs()
    c_out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "verify_c_output.txt")
    c_results = {}
    with open(c_out, encoding="utf-8") as fh:
        for line in fh:
            m = re.match(r"RESULT (\S+) (-?[\d.eE+-]+|nan|inf|-inf)", line.strip())
            if m:
                name, val = m.group(1), m.group(2)
                try:
                    c_results[name] = float(val)
                except ValueError:
                    c_results[name] = val

    npass, nfail = 0, 0
    failures = []
    for fname, fn in sorted(funcs.items()):
        if fname.startswith("_"):
            continue
        if fname not in c_results:
            failures.append((fname, "no C output"))
            nfail += 1
            continue
        params = fn.__code__.co_varnames[: fn.__code__.co_argcount]
        args = [value_for(p, i) for i, p in enumerate(params)]
        try:
            ref = float(np.asarray(fn(*args)).flat[0])
        except Exception as exc:  # noqa: BLE001
            failures.append((fname, f"ref error: {exc}"))
            nfail += 1
            continue
        got = c_results[fname]
        if isinstance(got, str):
            failures.append((fname, f"got {got}, ref {ref}"))
            nfail += 1
            continue
        tol = 1e-9 * max(1.0, abs(ref))
        if abs(ref - got) <= tol or (ref == 0.0 and abs(got) <= 1e-15):
            npass += 1
        else:
            failures.append((fname, f"got {got!r}, ref {ref!r} (diff {abs(ref-got):.3e})"))
            nfail += 1

    print(f"PASS {npass} / FAIL {nfail} / total {npass + nfail}")
    for name, why in failures[:40]:
        print(f"  FAIL {name}: {why}")


if __name__ == "__main__":
    main()