/* AUTO-GENERATED by gen_verify_kernels.py — do not edit */
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include "purce_src.h"

static int nfail = 0, npass = 0;

static double run_one(const char *name,
                        void (*fn)(int, const double *restrict, double *restrict),
                        double x, double y, double expected) {
    double out[1] = {0.0};
    double in1[1] = {x}, in2[1] = {y};
    /* generic 2-arg path used only when signature matches */
    (void)fn; (void)in1; (void)in2; (void)out; (void)expected;
    return 0.0;
}

static void check_chi_alt_dof(void) {
    double in0[1] = {10};
    double in1[1] = {2};
    double out[1] = {0.0};
    purce_src_chi_alt_dof_3ce38471(2, in0, in1, out);
    printf("RESULT chi_alt_dof %.17g\n", out[0]);
}

static void check_chi_alt_dof_max(void) {
    double in0[1] = {9};
    double in1[1] = {1};
    double out[1] = {0.0};
    purce_src_chi_alt_dof_max_a7a78f5e(2, in0, in1, out);
    printf("RESULT chi_alt_dof_max %.17g\n", out[0]);
}

static void check_chi_diff(void) {
    double in0[1] = {0.998};
    double in1[1] = {0.999};
    double out[1] = {0.0};
    purce_src_chi_diff_eefa0415(2, in0, in1, out);
    printf("RESULT chi_diff %.17g\n", out[0]);
}

static void check_chi_dof(void) {
    double in0[1] = {9};
    double in1[1] = {1};
    double out[1] = {0.0};
    purce_src_chi_dof_6fef7462(2, in0, in1, out);
    printf("RESULT chi_dof %.17g\n", out[0]);
}

static void check_chi_n_minus(void) {
    double in0[1] = {10};
    double in1[1] = {1};
    double out[1] = {0.0};
    purce_src_chi_n_minus_c441a630(2, in0, in1, out);
    printf("RESULT chi_n_minus %.17g\n", out[0]);
}

static void check_chi_reduced(void) {
    double in0[1] = {12};
    double in1[1] = {9};
    double out[1] = {0.0};
    purce_src_chi_reduced_6b1ed1e8(2, in0, in1, out);
    printf("RESULT chi_reduced %.17g\n", out[0]);
}

static void check_chi_reduced_alt(void) {
    double in0[1] = {12};
    double in1[1] = {9};
    double out[1] = {0.0};
    purce_src_chi_reduced_alt_d61eb52e(2, in0, in1, out);
    printf("RESULT chi_reduced_alt %.17g\n", out[0]);
}

static void check_chi_resid_sq(void) {
    double in0[1] = {1.0590000000000002};
    double out[1] = {0.0};
    purce_src_chi_resid_sq_4d0f5222(1, in0, out);
    printf("RESULT chi_resid_sq %.17g\n", out[0]);
}

static void check_chi_residuals(void) {
    double in0[1] = {0.01};
    double in1[1] = {0.00050000000000000001};
    double out[1] = {0.0};
    purce_src_chi_residuals_ce61bff4(2, in0, in1, out);
    printf("RESULT chi_residuals %.17g\n", out[0]);
}

static void check_chi_squared(void) {
    double in0[1] = {1.4399999999999999};
    double out[1] = {0.0};
    purce_src_chi_squared_7c8e3033(1, in0, out);
    printf("RESULT chi_squared %.17g\n", out[0]);
}

static void check_cvs_den_a(void) {
    double in0[1] = {0.96999999999999997};
    double in1[1] = {0.82999999999999996};
    double out[1] = {0.0};
    purce_src_cvs_den_a_b65a4875(2, in0, in1, out);
    printf("RESULT cvs_den_a %.17g\n", out[0]);
}

static void check_cvs_den_b(void) {
    double in0[1] = {0.60999999999999999};
    double in1[1] = {0.31};
    double out[1] = {0.0};
    purce_src_cvs_den_b_c209fe64(2, in0, in1, out);
    printf("RESULT cvs_den_b %.17g\n", out[0]);
}

static void check_cvs_num_a(void) {
    double in0[1] = {0.5};
    double in1[1] = {0.59999999999999998};
    double out[1] = {0.0};
    purce_src_cvs_num_a_70589ee8(2, in0, in1, out);
    printf("RESULT cvs_num_a %.17g\n", out[0]);
}

static void check_cvs_num_b(void) {
    double in0[1] = {0.69999999999999996};
    double in1[1] = {0.80000000000000004};
    double out[1] = {0.0};
    purce_src_cvs_num_b_b310441a(2, in0, in1, out);
    printf("RESULT cvs_num_b %.17g\n", out[0]);
}

static void check_cvs_numerator(void) {
    double in0[1] = {1.1000000000000001};
    double in1[1] = {1.5};
    double out[1] = {0.0};
    purce_src_cvs_numerator_9533d661(2, in0, in1, out);
    printf("RESULT cvs_numerator %.17g\n", out[0]);
}

static void check_cvs_score(void) {
    double in0[1] = {2.6000000000000001};
    double in1[1] = {1.325};
    double out[1] = {0.0};
    purce_src_cvs_score_5bac9461(2, in0, in1, out);
    printf("RESULT cvs_score %.17g\n", out[0]);
}

static void check_cvs_total(void) {
    double in0[1] = {1.6000000000000001};
    double in1[1] = {1.3999999999999999};
    double out[1] = {0.0};
    purce_src_cvs_total_119628ce(2, in0, in1, out);
    printf("RESULT cvs_total %.17g\n", out[0]);
}

static void check_cvs_total_max(void) {
    double in0[1] = {3};
    double in1[1] = {9.9999999999999998e-13};
    double out[1] = {0.0};
    purce_src_cvs_total_max_49a252a0(2, in0, in1, out);
    printf("RESULT cvs_total_max %.17g\n", out[0]);
}

static void check_cvs_wd_sd(void) {
    double in0[1] = {0.82999999999999996};
    double in1[1] = {0.80000000000000004};
    double out[1] = {0.0};
    purce_src_cvs_wd_sd_ffed4e1e(2, in0, in1, out);
    printf("RESULT cvs_wd_sd %.17g\n", out[0]);
}

static void check_cvs_wl_sl(void) {
    double in0[1] = {0.60999999999999999};
    double in1[1] = {0.69999999999999996};
    double out[1] = {0.0};
    purce_src_cvs_wl_sl_65d565ca(2, in0, in1, out);
    printf("RESULT cvs_wl_sl %.17g\n", out[0]);
}

static void check_cvs_wp_sp(void) {
    double in0[1] = {0.96999999999999997};
    double in1[1] = {0.90000000000000002};
    double out[1] = {0.0};
    purce_src_cvs_wp_sp_cc7ba620(2, in0, in1, out);
    printf("RESULT cvs_wp_sp %.17g\n", out[0]);
}

static void check_cvs_ws_ss(void) {
    double in0[1] = {0.31};
    double in1[1] = {0.59999999999999998};
    double out[1] = {0.0};
    purce_src_cvs_ws_ss_0fcc6119(2, in0, in1, out);
    printf("RESULT cvs_ws_ss %.17g\n", out[0]);
}

static void check_density_a_over_rs_den(void) {
    double in0[1] = {3.1415926535897931};
    double in1[1] = {18000};
    double out[1] = {0.0};
    purce_src_density_a_over_rs_den_d67f7aa5(2, in0, in1, out);
    printf("RESULT density_a_over_rs_den %.17g\n", out[0]);
}

static void check_density_a_over_rs_num(void) {
    double in0[1] = {15000000};
    double in1[1] = {1.0649999999999999};
    double out[1] = {0.0};
    purce_src_density_a_over_rs_num_dbe138f3(2, in0, in1, out);
    printf("RESULT density_a_over_rs_num %.17g\n", out[0]);
}

static void check_density_a_over_rs_transit(void) {
    double in0[1] = {760000000};
    double in1[1] = {30000000000};
    double out[1] = {0.0};
    purce_src_density_a_over_rs_transit_6ece4a52(2, in0, in1, out);
    printf("RESULT density_a_over_rs_transit %.17g\n", out[0]);
}

static void check_density_g_cgs(void) {
    double in0[1] = {250};
    double in1[1] = {100};
    double out[1] = {0.0};
    purce_src_density_g_cgs_659a9574(2, in0, in1, out);
    printf("RESULT density_g_cgs %.17g\n", out[0]);
}

static void check_density_g_cgs_div(void) {
    double in0[1] = {1.4e+29};
    double in1[1] = {5.6e+17};
    double out[1] = {0.0};
    purce_src_density_g_cgs_div_2a470693(2, in0, in1, out);
    printf("RESULT density_g_cgs_div %.17g\n", out[0]);
}

static void check_density_g_cgs_max(void) {
    double in0[1] = {25000};
    double in1[1] = {1};
    double out[1] = {0.0};
    purce_src_density_g_cgs_max_12048b9e(2, in0, in1, out);
    printf("RESULT density_g_cgs_max %.17g\n", out[0]);
}

static void check_density_g_den(void) {
    double in0[1] = {750000000};
    double out[1] = {0.0};
    purce_src_density_g_den_a8d7e46a(1, in0, out);
    printf("RESULT density_g_den %.17g\n", out[0]);
}

static void check_density_g_num(void) {
    double in0[1] = {6.6742999999999994e-11};
    double in1[1] = {2.2e+30};
    double out[1] = {0.0};
    purce_src_density_g_num_93b6e99f(2, in0, in1, out);
    printf("RESULT density_g_num %.17g\n", out[0]);
}

static void check_density_logg(void) {
    double in0[1] = {25000};
    double out[1] = {0.0};
    purce_src_density_logg_3eed90ec(1, in0, out);
    printf("RESULT density_logg %.17g\n", out[0]);
}

static void check_density_one_plus_k(void) {
    double in0[1] = {0.065000000000000002};
    double in1[1] = {1};
    double out[1] = {0.0};
    purce_src_density_one_plus_k_aef82505(2, in0, in1, out);
    printf("RESULT density_one_plus_k %.17g\n", out[0]);
}

static void check_density_ratio(void) {
    double in0[1] = {4000};
    double in1[1] = {1.4990000000000001};
    double out[1] = {0.0};
    purce_src_density_ratio_67fcbc7c(2, in0, in1, out);
    printf("RESULT density_ratio %.17g\n", out[0]);
}

static void check_density_rho_coeff(void) {
    double in0[1] = {9.4247779607693793};
    double in1[1] = {1500000000000};
    double out[1] = {0.0};
    purce_src_density_rho_coeff_4b89eabc(2, in0, in1, out);
    printf("RESULT density_rho_coeff %.17g\n", out[0]);
}

static void check_density_rho_den(void) {
    double in0[1] = {6.6742999999999994e-11};
    double in1[1] = {225000000000000};
    double out[1] = {0.0};
    purce_src_density_rho_den_e36e01d8(2, in0, in1, out);
    printf("RESULT density_rho_den %.17g\n", out[0]);
}

static void check_density_rho_pow_a(void) {
    double in0[1] = {40};
    double in1[1] = {3};
    double out[1] = {0.0};
    purce_src_density_rho_pow_a_170d3d0c(2, in0, in1, out);
    printf("RESULT density_rho_pow_a %.17g\n", out[0]);
}

static void check_density_rho_pow_p(void) {
    double in0[1] = {15000000};
    double out[1] = {0.0};
    purce_src_density_rho_pow_p_4b908d4e(1, in0, out);
    printf("RESULT density_rho_pow_p %.17g\n", out[0]);
}

static void check_density_rho_tic_gcc(void) {
    double in0[1] = {4500};
    double in1[1] = {0.001};
    double out[1] = {0.0};
    purce_src_density_rho_tic_gcc_190d4c2c(2, in0, in1, out);
    printf("RESULT density_rho_tic_gcc %.17g\n", out[0]);
}

static void check_density_rho_tic_kgm3(void) {
    double in0[1] = {2.2e+30};
    double in1[1] = {1.7999999999999999e+27};
    double out[1] = {0.0};
    purce_src_density_rho_tic_kgm3_ab7e90f2(2, in0, in1, out);
    printf("RESULT density_rho_tic_kgm3 %.17g\n", out[0]);
}

static void check_density_rho_tic_max(void) {
    double in0[1] = {3500};
    double in1[1] = {9.9999999999999998e-13};
    double out[1] = {0.0};
    purce_src_density_rho_tic_max_a44dbdda(2, in0, in1, out);
    printf("RESULT density_rho_tic_max %.17g\n", out[0]);
}

static void check_density_rho_transit_gcc(void) {
    double in0[1] = {4500};
    double in1[1] = {0.001};
    double out[1] = {0.0};
    purce_src_density_rho_transit_gcc_654aae3e(2, in0, in1, out);
    printf("RESULT density_rho_transit_gcc %.17g\n", out[0]);
}

static void check_density_rho_transit_kgm3(void) {
    double in0[1] = {6.2799999999999999e-12};
    double in1[1] = {64000};
    double out[1] = {0.0};
    purce_src_density_rho_transit_kgm3_24e14fe1(2, in0, in1, out);
    printf("RESULT density_rho_transit_kgm3 %.17g\n", out[0]);
}

static void check_density_tdur_max(void) {
    double in0[1] = {18000};
    double in1[1] = {1};
    double out[1] = {0.0};
    purce_src_density_tdur_max_730f8bd8(2, in0, in1, out);
    printf("RESULT density_tdur_max %.17g\n", out[0]);
}

static void check_density_vol(void) {
    double in0[1] = {4.1879999999999997};
    double in1[1] = {4.2000000000000002e+26};
    double out[1] = {0.0};
    purce_src_density_vol_5c746dc2(2, in0, in1, out);
    printf("RESULT density_vol %.17g\n", out[0]);
}

static void check_density_vol_coeff(void) {
    double in0[1] = {1.3333333333333333};
    double in1[1] = {3.1415926535897931};
    double out[1] = {0.0};
    purce_src_density_vol_coeff_4509092e(2, in0, in1, out);
    printf("RESULT density_vol_coeff %.17g\n", out[0]);
}

static void check_density_vol_pow(void) {
    double in0[1] = {750000000};
    double out[1] = {0.0};
    purce_src_density_vol_pow_3c8c6d79(1, in0, out);
    printf("RESULT density_vol_pow %.17g\n", out[0]);
}

static void check_depth_cons_chi_sub(void) {
    double in0[1] = {1.2};
    double in1[1] = {1};
    double out[1] = {0.0};
    purce_src_depth_cons_chi_sub_bcac6c05(2, in0, in1, out);
    printf("RESULT depth_cons_chi_sub %.17g\n", out[0]);
}

static void check_depth_cons_norm_sub(void) {
    double in0[1] = {10};
    double in1[1] = {1};
    double out[1] = {0.0};
    purce_src_depth_cons_norm_sub_22cb9d45(2, in0, in1, out);
    printf("RESULT depth_cons_norm_sub %.17g\n", out[0]);
}

static void check_depth_cons_ratio(void) {
    double in0[1] = {0.20000000000000001};
    double in1[1] = {9};
    double out[1] = {0.0};
    purce_src_depth_cons_ratio_5ef9b59e(2, in0, in1, out);
    printf("RESULT depth_cons_ratio %.17g\n", out[0]);
}

static void check_depth_cons_sub(void) {
    double in0[1] = {1};
    double in1[1] = {0.69999999999999996};
    double out[1] = {0.0};
    purce_src_depth_cons_sub_565329b3(2, in0, in1, out);
    printf("RESULT depth_cons_sub %.17g\n", out[0]);
}

static void check_depth_consistency_s(void) {
    double in0[1] = {0.29999999999999999};
    double in1[1] = {0};
    double in2[1] = {1};
    double out[1] = {0.0};
    purce_src_depth_consistency_s_03d9d99c(3, in0, in1, in2, out);
    printf("RESULT depth_consistency_s %.17g\n", out[0]);
}

static void check_depths_chi2_reduced(void) {
    double in0[1] = {0.69999999999999996};
    double out[1] = {0.0};
    purce_src_depths_chi2_reduced_e5f1ac75(1, in0, out);
    printf("RESULT depths_chi2_reduced %.17g\n", out[0]);
}

static void check_depths_cv(void) {
    double in0[1] = {0.72599999999999998};
    double in1[1] = {1.2349999999999999};
    double out[1] = {0.0};
    purce_src_depths_cv_9c31aae2(2, in0, in1, out);
    printf("RESULT depths_cv %.17g\n", out[0]);
}

static void check_depths_err_sq(void) {
    double in0[1] = {0.00029999999999999997};
    double out[1] = {0.0};
    purce_src_depths_err_sq_2c42f68b(1, in0, out);
    printf("RESULT depths_err_sq %.17g\n", out[0]);
}

static void check_depths_mean(void) {
    double in0[1] = {0.0041999999999999997};
    double out[1] = {0.0};
    purce_src_depths_mean_df8d177b(1, in0, out);
    printf("RESULT depths_mean %.17g\n", out[0]);
}

static void check_depths_mu_max(void) {
    double in0[1] = {0.0041999999999999997};
    double in1[1] = {9.9999999999999998e-13};
    double out[1] = {0.0};
    purce_src_depths_mu_max_fc955b42(2, in0, in1, out);
    printf("RESULT depths_mu_max %.17g\n", out[0]);
}

static void check_depths_ratio(void) {
    double in0[1] = {1.4399999999999999};
    double in1[1] = {8.9999999999999999e-08};
    double out[1] = {0.0};
    purce_src_depths_ratio_3ece5e80(2, in0, in1, out);
    printf("RESULT depths_ratio %.17g\n", out[0]);
}

static void check_depths_resid(void) {
    double in0[1] = {0.0041999999999999997};
    double in1[1] = {0.0041999999999999997};
    double out[1] = {0.0};
    purce_src_depths_resid_13703a6c(2, in0, in1, out);
    printf("RESULT depths_resid %.17g\n", out[0]);
}

static void check_depths_resid_sq(void) {
    double in0[1] = {0.20000000000000001};
    double out[1] = {0.0};
    purce_src_depths_resid_sq_96f61960(1, in0, out);
    printf("RESULT depths_resid_sq %.17g\n", out[0]);
}

static void check_depths_std_scale(void) {
    double in0[1] = {1.0720000000000001};
    double in1[1] = {10};
    double out[1] = {0.0};
    purce_src_depths_std_scale_660cf032(2, in0, in1, out);
    printf("RESULT depths_std_scale %.17g\n", out[0]);
}

static void check_depths_std_scale2(void) {
    double in0[1] = {1.496};
    double in1[1] = {1.0899999999999999};
    double out[1] = {0.0};
    purce_src_depths_std_scale2_1919b9d4(2, in0, in1, out);
    printf("RESULT depths_std_scale2 %.17g\n", out[0]);
}

static void check_depths_std_sqrt(void) {
    double in0[1] = {0.92399999999999993};
    double out[1] = {0.0};
    purce_src_depths_std_sqrt_4bf245c3(1, in0, out);
    printf("RESULT depths_std_sqrt %.17g\n", out[0]);
}

static void check_depths_var_pop(void) {
    double in0[1] = {0.0041999999999999997};
    double out[1] = {0.0};
    purce_src_depths_var_pop_6c1f64c8(1, in0, out);
    printf("RESULT depths_var_pop %.17g\n", out[0]);
}

static void check_geometry_cons_k_sq_max(void) {
    double in0[1] = {0.0042249999999999996};
    double in1[1] = {9.9999999999999998e-13};
    double out[1] = {0.0};
    purce_src_geometry_cons_k_sq_max_72c33749(2, in0, in1, out);
    printf("RESULT geometry_cons_k_sq_max %.17g\n", out[0]);
}

static void check_geometry_cons_resid_abs(void) {
    double in0[1] = {0.29999999999999999};
    double out[1] = {0.0};
    purce_src_geometry_cons_resid_abs_58db32c0(1, in0, out);
    printf("RESULT geometry_cons_resid_abs %.17g\n", out[0]);
}

static void check_geometry_cons_resid_div(void) {
    double in0[1] = {0.01};
    double in1[1] = {1.4350000000000001};
    double out[1] = {0.0};
    purce_src_geometry_cons_resid_div_7e29062d(2, in0, in1, out);
    printf("RESULT geometry_cons_resid_div %.17g\n", out[0]);
}

static void check_geometry_cons_resid_pct(void) {
    double in0[1] = {0.02};
    double in1[1] = {100};
    double out[1] = {0.0};
    purce_src_geometry_cons_resid_pct_cdf32450(2, in0, in1, out);
    printf("RESULT geometry_cons_resid_pct %.17g\n", out[0]);
}

static void check_geometry_cons_resid_sub(void) {
    double in0[1] = {0.0041999999999999997};
    double in1[1] = {0.0042249999999999996};
    double out[1] = {0.0};
    purce_src_geometry_cons_resid_sub_2bc0676c(2, in0, in1, out);
    printf("RESULT geometry_cons_resid_sub %.17g\n", out[0]);
}

static void check_geometry_delta_clamped(void) {
    double in0[1] = {0.0041999999999999997};
    double in1[1] = {9.9999999999999998e-13};
    double out[1] = {0.0};
    purce_src_geometry_delta_clamped_f1c04251(2, in0, in1, out);
    printf("RESULT geometry_delta_clamped %.17g\n", out[0]);
}

static void check_geometry_k(void) {
    double in0[1] = {0.0041999999999999997};
    double out[1] = {0.0};
    purce_src_geometry_k_a714c37c(1, in0, out);
    printf("RESULT geometry_k %.17g\n", out[0]);
}

static void check_geometry_k_sq(void) {
    double in0[1] = {0.065000000000000002};
    double out[1] = {0.0};
    purce_src_geometry_k_sq_a9e9f55b(1, in0, out);
    printf("RESULT geometry_k_sq %.17g\n", out[0]);
}

static void check_geometry_ld_cen_sub(void) {
    double in0[1] = {1};
    double in1[1] = {0};
    double out[1] = {0.0};
    purce_src_geometry_ld_cen_sub_3e670b09(2, in0, in1, out);
    printf("RESULT geometry_ld_cen_sub %.17g\n", out[0]);
}

static void check_geometry_ld_cen_sub2(void) {
    double in0[1] = {0.84999999999999998};
    double in1[1] = {0};
    double out[1] = {0.0};
    purce_src_geometry_ld_cen_sub2_30a34eea(2, in0, in1, out);
    printf("RESULT geometry_ld_cen_sub2 %.17g\n", out[0]);
}

static void check_geometry_ld_corrected(void) {
    double in0[1] = {2.6000000000000001};
    double in1[1] = {0.80000000000000004};
    double out[1] = {0.0};
    purce_src_geometry_ld_corrected_d478fad9(2, in0, in1, out);
    printf("RESULT geometry_ld_corrected %.17g\n", out[0]);
}

static void check_geometry_ld_i_cen(void) {
    double in0[1] = {0.90000000000000002};
    double in1[1] = {0.10000000000000001};
    double out[1] = {0.0};
    purce_src_geometry_ld_i_cen_1d5b45bc(2, in0, in1, out);
    printf("RESULT geometry_ld_i_cen %.17g\n", out[0]);
}

static void check_geometry_ld_i_mean(void) {
    double in0[1] = {0.90000000000000002};
    double in1[1] = {0.10000000000000001};
    double out[1] = {0.0};
    purce_src_geometry_ld_i_mean_73906914(2, in0, in1, out);
    printf("RESULT geometry_ld_i_mean %.17g\n", out[0]);
}

static void check_geometry_ld_numerator(void) {
    double in0[1] = {0.0042249999999999996};
    double in1[1] = {1};
    double out[1] = {0.0};
    purce_src_geometry_ld_numerator_052155c8(2, in0, in1, out);
    printf("RESULT geometry_ld_numerator %.17g\n", out[0]);
}

static void check_geometry_ld_sub(void) {
    double in0[1] = {1};
    double in1[1] = {0.14999999999999999};
    double out[1] = {0.0};
    purce_src_geometry_ld_sub_5dd1c288(2, in0, in1, out);
    printf("RESULT geometry_ld_sub %.17g\n", out[0]);
}

static void check_geometry_ld_sub2(void) {
    double in0[1] = {0.84999999999999998};
    double in1[1] = {0.025000000000000001};
    double out[1] = {0.0};
    purce_src_geometry_ld_sub2_f9f8a586(2, in0, in1, out);
    printf("RESULT geometry_ld_sub2 %.17g\n", out[0]);
}

static void check_geometry_ld_u1cen_term(void) {
    double in0[1] = {0.45000000000000001};
    double in1[1] = {0};
    double out[1] = {0.0};
    purce_src_geometry_ld_u1cen_term_97c1eb73(2, in0, in1, out);
    printf("RESULT geometry_ld_u1cen_term %.17g\n", out[0]);
}

static void check_geometry_ld_u2cen_term(void) {
    double in0[1] = {0.14999999999999999};
    double in1[1] = {0};
    double out[1] = {0.0};
    purce_src_geometry_ld_u2cen_term_86c94295(2, in0, in1, out);
    printf("RESULT geometry_ld_u2cen_term %.17g\n", out[0]);
}

static void check_geometry_ld_zeropow(void) {
    double in0[1] = {1.2349999999999999};
    double in1[1] = {1};
    double out[1] = {0.0};
    purce_src_geometry_ld_zeropow_3e6ae1b6(2, in0, in1, out);
    printf("RESULT geometry_ld_zeropow %.17g\n", out[0]);
}

static void check_geometry_ld_zeropow_diff(void) {
    double in0[1] = {1};
    double in1[1] = {0.79400000000000004};
    double out[1] = {0.0};
    purce_src_geometry_ld_zeropow_diff_e2b6d51d(2, in0, in1, out);
    printf("RESULT geometry_ld_zeropow_diff %.17g\n", out[0]);
}

static void check_geometry_rp_earth(void) {
    double in0[1] = {49000000};
    double in1[1] = {6378100};
    double out[1] = {0.0};
    purce_src_geometry_rp_earth_d541fdd4(2, in0, in1, out);
    printf("RESULT geometry_rp_earth %.17g\n", out[0]);
}

static void check_geometry_rp_m(void) {
    double in0[1] = {0.065000000000000002};
    double in1[1] = {750000000};
    double out[1] = {0.0};
    purce_src_geometry_rp_m_0bc355fa(2, in0, in1, out);
    printf("RESULT geometry_rp_m %.17g\n", out[0]);
}

static void check_geometry_u1_term(void) {
    double in0[1] = {0.45000000000000001};
    double in1[1] = {0.33333333333333331};
    double out[1] = {0.0};
    purce_src_geometry_u1_term_0e734a16(2, in0, in1, out);
    printf("RESULT geometry_u1_term %.17g\n", out[0]);
}

static void check_geometry_u2_term(void) {
    double in0[1] = {0.14999999999999999};
    double in1[1] = {0.16666666666666666};
    double out[1] = {0.0};
    purce_src_geometry_u2_term_a239ecee(2, in0, in1, out);
    printf("RESULT geometry_u2_term %.17g\n", out[0]);
}

static void check_kepler_a3(void) {
    double in0[1] = {3.0000000000000002e+34};
    double in1[1] = {39.479999999999997};
    double out[1] = {0.0};
    purce_src_kepler_a3_08bcd3f7(2, in0, in1, out);
    printf("RESULT kepler_a3 %.17g\n", out[0]);
}

static void check_kepler_a3_num(void) {
    double in0[1] = {1.33e+20};
    double in1[1] = {225000000000000};
    double out[1] = {0.0};
    purce_src_kepler_a3_num_d9ffca74(2, in0, in1, out);
    printf("RESULT kepler_a3_num %.17g\n", out[0]);
}

static void check_kepler_a_au(void) {
    double in0[1] = {30000000000};
    double in1[1] = {149597870700};
    double out[1] = {0.0};
    purce_src_kepler_a_au_e9f15bbc(2, in0, in1, out);
    printf("RESULT kepler_a_au %.17g\n", out[0]);
}

static void check_kepler_a_au_cubed(void) {
    double in0[1] = {0.20000000000000001};
    double out[1] = {0.0};
    purce_src_kepler_a_au_cubed_f9db1b7f(1, in0, out);
    printf("RESULT kepler_a_au_cubed %.17g\n", out[0]);
}

static void check_kepler_a_au_max(void) {
    double in0[1] = {0.0080000000000000002};
    double in1[1] = {9.9999999999999998e-13};
    double out[1] = {0.0};
    purce_src_kepler_a_au_max_2517d228(2, in0, in1, out);
    printf("RESULT kepler_a_au_max %.17g\n", out[0]);
}

static void check_kepler_a_m(void) {
    double in0[1] = {7.6000000000000006e+32};
    double in1[1] = {0.33333333333333331};
    double out[1] = {0.0};
    purce_src_kepler_a_m_f674c7f2(2, in0, in1, out);
    printf("RESULT kepler_a_m %.17g\n", out[0]);
}

static void check_kepler_a_m_cubed(void) {
    double in0[1] = {30000000000};
    double out[1] = {0.0};
    purce_src_kepler_a_m_cubed_9f77db4b(1, in0, out);
    printf("RESULT kepler_a_m_cubed %.17g\n", out[0]);
}

static void check_kepler_denominator(void) {
    double in0[1] = {4};
    double in1[1] = {0.84000000000000008};
    double out[1] = {0.0};
    purce_src_kepler_denominator_ff600e16(2, in0, in1, out);
    printf("RESULT kepler_denominator %.17g\n", out[0]);
}

static void check_kepler_diff_abs(void) {
    double in0[1] = {0.01};
    double out[1] = {0.0};
    purce_src_kepler_diff_abs_48aeecda(1, in0, out);
    printf("RESULT kepler_diff_abs %.17g\n", out[0]);
}

static void check_kepler_diff_si(void) {
    double in0[1] = {1.3559999999999999};
    double in1[1] = {1.3109999999999999};
    double out[1] = {0.0};
    purce_src_kepler_diff_si_ebc5792c(2, in0, in1, out);
    printf("RESULT kepler_diff_si %.17g\n", out[0]);
}

static void check_kepler_diff_solar(void) {
    double in0[1] = {0.69999999999999996};
    double in1[1] = {0.90000000000000002};
    double out[1] = {0.0};
    purce_src_kepler_diff_solar_01a0f6f9(2, in0, in1, out);
    printf("RESULT kepler_diff_solar %.17g\n", out[0]);
}

static void check_kepler_diff_solar_abs(void) {
    double in0[1] = {0.01};
    double out[1] = {0.0};
    purce_src_kepler_diff_solar_abs_7f8924f3(1, in0, out);
    printf("RESULT kepler_diff_solar_abs %.17g\n", out[0]);
}

static void check_kepler_expect_max(void) {
    double in0[1] = {0.90000000000000002};
    double in1[1] = {9.9999999999999998e-13};
    double out[1] = {0.0};
    purce_src_kepler_expect_max_34d0f1bf(2, in0, in1, out);
    printf("RESULT kepler_expect_max %.17g\n", out[0]);
}

static void check_kepler_expect_solar(void) {
    double in0[1] = {1};
    double in1[1] = {1.1000000000000001};
    double out[1] = {0.0};
    purce_src_kepler_expect_solar_bfe8eecc(2, in0, in1, out);
    printf("RESULT kepler_expect_solar %.17g\n", out[0]);
}

static void check_kepler_expected_si(void) {
    double in0[1] = {39.478000000000002};
    double in1[1] = {1.33e+20};
    double out[1] = {0.0};
    purce_src_kepler_expected_si_983db113(2, in0, in1, out);
    printf("RESULT kepler_expected_si %.17g\n", out[0]);
}

static void check_kepler_gm(void) {
    double in0[1] = {6.6742999999999994e-11};
    double in1[1] = {1.1000000000000001};
    double out[1] = {0.0};
    purce_src_kepler_gm_cce91793(2, in0, in1, out);
    printf("RESULT kepler_gm %.17g\n", out[0]);
}

static void check_kepler_gm_full(void) {
    double in0[1] = {6.7000000000000001e-11};
    double in1[1] = {1.9884e+30};
    double out[1] = {0.0};
    purce_src_kepler_gm_full_aa78c33d(2, in0, in1, out);
    printf("RESULT kepler_gm_full %.17g\n", out[0]);
}

static void check_kepler_norm_diff_si(void) {
    double in0[1] = {0.01};
    double in1[1] = {1.3109999999999999};
    double out[1] = {0.0};
    purce_src_kepler_norm_diff_si_4ed6e8b4(2, in0, in1, out);
    printf("RESULT kepler_norm_diff_si %.17g\n", out[0]);
}

static void check_kepler_norm_solar(void) {
    double in0[1] = {0.01};
    double in1[1] = {0.90000000000000002};
    double out[1] = {0.0};
    purce_src_kepler_norm_solar_167c610a(2, in0, in1, out);
    printf("RESULT kepler_norm_solar %.17g\n", out[0]);
}

static void check_kepler_p_sec_sq(void) {
    double in0[1] = {15000000};
    double out[1] = {0.0};
    purce_src_kepler_p_sec_sq_d786d462(1, in0, out);
    printf("RESULT kepler_p_sec_sq %.17g\n", out[0]);
}

static void check_kepler_p_sec_sq_2(void) {
    double in0[1] = {15000000};
    double out[1] = {0.0};
    purce_src_kepler_p_sec_sq_2_ed24ce94(1, in0, out);
    printf("RESULT kepler_p_sec_sq_2 %.17g\n", out[0]);
}

static void check_kepler_p_yr(void) {
    double in0[1] = {12.5};
    double in1[1] = {0.0027378507871321013};
    double out[1] = {0.0};
    purce_src_kepler_p_yr_8a8b968e(2, in0, in1, out);
    printf("RESULT kepler_p_yr %.17g\n", out[0]);
}

static void check_kepler_p_yr_sq(void) {
    double in0[1] = {0.81600000000000006};
    double out[1] = {0.0};
    purce_src_kepler_p_yr_sq_dad6e103(1, in0, out);
    printf("RESULT kepler_p_yr_sq %.17g\n", out[0]);
}

static void check_kepler_pi_sq(void) {
    double in0[1] = {3.1415926535897931};
    double out[1] = {0.0};
    purce_src_kepler_pi_sq_0e1b6818(1, in0, out);
    printf("RESULT kepler_pi_sq %.17g\n", out[0]);
}

static void check_kepler_ratio_si(void) {
    double in0[1] = {225000000000000};
    double in1[1] = {2.6999999999999999e+31};
    double out[1] = {0.0};
    purce_src_kepler_ratio_si_30d9bfbf(2, in0, in1, out);
    printf("RESULT kepler_ratio_si %.17g\n", out[0]);
}

static void check_kepler_ratio_solar(void) {
    double in0[1] = {0.0011999999999999999};
    double in1[1] = {0.0080000000000000002};
    double out[1] = {0.0};
    purce_src_kepler_ratio_solar_19fb5df0(2, in0, in1, out);
    printf("RESULT kepler_ratio_solar %.17g\n", out[0]);
}

static void check_kepler_residual_si(void) {
    double in0[1] = {0.010999999999999999};
    double in1[1] = {100};
    double out[1] = {0.0};
    purce_src_kepler_residual_si_3df9ed0f(2, in0, in1, out);
    printf("RESULT kepler_residual_si %.17g\n", out[0]);
}

static void check_kepler_residual_solar(void) {
    double in0[1] = {0.010999999999999999};
    double in1[1] = {100};
    double out[1] = {0.0};
    purce_src_kepler_residual_solar_cfad1534(2, in0, in1, out);
    printf("RESULT kepler_residual_solar %.17g\n", out[0]);
}

static void check_probability_a_over_rs(void) {
    double in0[1] = {30000000000};
    double in1[1] = {750000000};
    double out[1] = {0.0};
    purce_src_probability_a_over_rs_b15534e1(2, in0, in1, out);
    printf("RESULT probability_a_over_rs %.17g\n", out[0]);
}

static void check_probability_b(void) {
    double in0[1] = {0};
    double out[1] = {0.0};
    purce_src_probability_b_a73daf1d(1, in0, out);
    printf("RESULT probability_b %.17g\n", out[0]);
}

static void check_probability_b_clamped(void) {
    double in0[1] = {0};
    double out[1] = {0.0};
    purce_src_probability_b_clamped_5af44d93(1, in0, out);
    printf("RESULT probability_b_clamped %.17g\n", out[0]);
}

static void check_probability_b_sq(void) {
    double in0[1] = {1.1339999999999999};
    double in1[1] = {368.60000000000002};
    double out[1] = {0.0};
    purce_src_probability_b_sq_feea2f20(2, in0, in1, out);
    printf("RESULT probability_b_sq %.17g\n", out[0]);
}

static void check_probability_cos_clamped(void) {
    double in0[1] = {0.5};
    double in1[1] = {1};
    double out[1] = {0.0};
    purce_src_probability_cos_clamped_74a31456(2, in0, in1, out);
    printf("RESULT probability_cos_clamped %.17g\n", out[0]);
}

static void check_probability_cos_max(void) {
    double in0[1] = {760000000};
    double in1[1] = {30000000000};
    double out[1] = {0.0};
    purce_src_probability_cos_max_9fb76630(2, in0, in1, out);
    printf("RESULT probability_cos_max %.17g\n", out[0]);
}

static void check_probability_den(void) {
    double in0[1] = {30000000000};
    double in1[1] = {760000000};
    double out[1] = {0.0};
    purce_src_probability_den_dc355a2e(2, in0, in1, out);
    printf("RESULT probability_den %.17g\n", out[0]);
}

static void check_probability_ingress_den(void) {
    double in0[1] = {1.0649999999999999};
    double in1[1] = {9.9999999999999998e-13};
    double out[1] = {0.0};
    purce_src_probability_ingress_den_ca99298e(2, in0, in1, out);
    printf("RESULT probability_ingress_den %.17g\n", out[0]);
}

static void check_probability_ingress_hrs(void) {
    double in0[1] = {5};
    double in1[1] = {0.69999999999999996};
    double out[1] = {0.0};
    purce_src_probability_ingress_hrs_01a860d8(2, in0, in1, out);
    printf("RESULT probability_ingress_hrs %.17g\n", out[0]);
}

static void check_probability_ingress_ratio(void) {
    double in0[1] = {0.065000000000000002};
    double in1[1] = {30000000000};
    double out[1] = {0.0};
    purce_src_probability_ingress_ratio_2703541e(2, in0, in1, out);
    printf("RESULT probability_ingress_ratio %.17g\n", out[0]);
}

static void check_probability_num(void) {
    double in0[1] = {750000000};
    double in1[1] = {6500000};
    double out[1] = {0.0};
    purce_src_probability_num_ab1d7dec(2, in0, in1, out);
    printf("RESULT probability_num %.17g\n", out[0]);
}

static void check_probability_one_plus_k(void) {
    double in0[1] = {0.065000000000000002};
    double in1[1] = {1};
    double out[1] = {0.0};
    purce_src_probability_one_plus_k_92c81f69(2, in0, in1, out);
    printf("RESULT probability_one_plus_k %.17g\n", out[0]);
}

static void check_probability_opk_sq(void) {
    double in0[1] = {1.0649999999999999};
    double out[1] = {0.0};
    purce_src_probability_opk_sq_e716b82f(1, in0, out);
    printf("RESULT probability_opk_sq %.17g\n", out[0]);
}

static void check_probability_p_max(void) {
    double in0[1] = {15000000};
    double in1[1] = {1};
    double out[1] = {0.0};
    purce_src_probability_p_max_bdde5587(2, in0, in1, out);
    printf("RESULT probability_p_max %.17g\n", out[0]);
}

static void check_probability_ptr(void) {
    double in0[1] = {760000000};
    double in1[1] = {30000000000};
    double out[1] = {0.0};
    purce_src_probability_ptr_ca056473(2, in0, in1, out);
    printf("RESULT probability_ptr %.17g\n", out[0]);
}

static void check_probability_ptr_clamped(void) {
    double in0[1] = {0.59999999999999998};
    double in1[1] = {1};
    double out[1] = {0.0};
    purce_src_probability_ptr_clamped_360acecd(2, in0, in1, out);
    printf("RESULT probability_ptr_clamped %.17g\n", out[0]);
}

static void check_probability_rstar_max(void) {
    double in0[1] = {750000000};
    double in1[1] = {9.9999999999999998e-13};
    double out[1] = {0.0};
    purce_src_probability_rstar_max_772c4022(2, in0, in1, out);
    printf("RESULT probability_rstar_max %.17g\n", out[0]);
}

static void check_probability_sin(void) {
    double in0[1] = {0.5};
    double out[1] = {0.0};
    purce_src_probability_sin_9b57fd41(1, in0, out);
    printf("RESULT probability_sin %.17g\n", out[0]);
}

static void check_probability_sin_arg(void) {
    double in0[1] = {0.5};
    double in1[1] = {3.1415926535897931};
    double out[1] = {0.0};
    purce_src_probability_sin_arg_e4b6b0e4(2, in0, in1, out);
    printf("RESULT probability_sin_arg %.17g\n", out[0]);
}

static void check_probability_sin_prod(void) {
    double in0[1] = {3.1415926535897931};
    double in1[1] = {0.69999999999999996};
    double out[1] = {0.0};
    purce_src_probability_sin_prod_08cbc925(2, in0, in1, out);
    printf("RESULT probability_sin_prod %.17g\n", out[0]);
}

static void check_probability_sin_ratio(void) {
    double in0[1] = {18000};
    double in1[1] = {12.5};
    double out[1] = {0.0};
    purce_src_probability_sin_ratio_bc35f349(2, in0, in1, out);
    printf("RESULT probability_sin_ratio %.17g\n", out[0]);
}

static void check_probability_sin_term(void) {
    double in0[1] = {40};
    double in1[1] = {0.47899999999999998};
    double out[1] = {0.0};
    purce_src_probability_sin_term_0841a329(2, in0, in1, out);
    printf("RESULT probability_sin_term %.17g\n", out[0]);
}

static void check_probability_st_sq(void) {
    double in0[1] = {19.199999999999999};
    double out[1] = {0.0};
    purce_src_probability_st_sq_2ff19abf(1, in0, out);
    printf("RESULT probability_st_sq %.17g\n", out[0]);
}

static void check_welch_delta(void) {
    double in0[1] = {0.0040000000000000001};
    double in1[1] = {0.0041000000000000003};
    double out[1] = {0.0};
    purce_src_welch_delta_17387ce5(2, in0, in1, out);
    printf("RESULT welch_delta %.17g\n", out[0]);
}

static void check_welch_delta_abs(void) {
    double in0[1] = {0.0041999999999999997};
    double out[1] = {0.0};
    purce_src_welch_delta_abs_0960a38c(1, in0, out);
    printf("RESULT welch_delta_abs %.17g\n", out[0]);
}

static void check_welch_delta_sigma(void) {
    double in0[1] = {0.0001};
    double in1[1] = {0.61399999999999999};
    double out[1] = {0.0};
    purce_src_welch_delta_sigma_f313a4f6(2, in0, in1, out);
    printf("RESULT welch_delta_sigma %.17g\n", out[0]);
}

static void check_welch_den_max(void) {
    double in0[1] = {0.00020000000000000001};
    double in1[1] = {9.9999999999999998e-13};
    double out[1] = {0.0};
    purce_src_welch_den_max_0fb457e3(2, in0, in1, out);
    printf("RESULT welch_den_max %.17g\n", out[0]);
}

static void check_welch_den_sqrt(void) {
    double in0[1] = {4.0000000000000001e-08};
    double out[1] = {0.0};
    purce_src_welch_den_sqrt_8ab27c36(1, in0, out);
    printf("RESULT welch_den_sqrt %.17g\n", out[0]);
}

static void check_welch_se(void) {
    double in0[1] = {0.00029999999999999997};
    double in1[1] = {2.2360000000000002};
    double out[1] = {0.0};
    purce_src_welch_se_a0c7c845(2, in0, in1, out);
    printf("RESULT welch_se %.17g\n", out[0]);
}

static void check_welch_se_e_sq(void) {
    double in0[1] = {8.8999999999999995e-05};
    double out[1] = {0.0};
    purce_src_welch_se_e_sq_a7a4bede(1, in0, out);
    printf("RESULT welch_se_e_sq %.17g\n", out[0]);
}

static void check_welch_se_o_sq(void) {
    double in0[1] = {8.8999999999999995e-05};
    double out[1] = {0.0};
    purce_src_welch_se_o_sq_9514abf3(1, in0, out);
    printf("RESULT welch_se_o_sq %.17g\n", out[0]);
}

static void check_welch_sqrt_n(void) {
    double in0[1] = {10};
    double out[1] = {0.0};
    purce_src_welch_sqrt_n_f3352330(1, in0, out);
    printf("RESULT welch_sqrt_n %.17g\n", out[0]);
}

static void check_welch_var_sum(void) {
    double in0[1] = {7.8999999999999996e-09};
    double in1[1] = {7.8999999999999996e-09};
    double out[1] = {0.0};
    purce_src_welch_var_sum_df18ee1d(2, in0, in1, out);
    printf("RESULT welch_var_sum %.17g\n", out[0]);
}

int main(void) {
    check_chi_alt_dof();
    check_chi_alt_dof_max();
    check_chi_diff();
    check_chi_dof();
    check_chi_n_minus();
    check_chi_reduced();
    check_chi_reduced_alt();
    check_chi_resid_sq();
    check_chi_residuals();
    check_chi_squared();
    check_cvs_den_a();
    check_cvs_den_b();
    check_cvs_num_a();
    check_cvs_num_b();
    check_cvs_numerator();
    check_cvs_score();
    check_cvs_total();
    check_cvs_total_max();
    check_cvs_wd_sd();
    check_cvs_wl_sl();
    check_cvs_wp_sp();
    check_cvs_ws_ss();
    check_density_a_over_rs_den();
    check_density_a_over_rs_num();
    check_density_a_over_rs_transit();
    check_density_g_cgs();
    check_density_g_cgs_div();
    check_density_g_cgs_max();
    check_density_g_den();
    check_density_g_num();
    check_density_logg();
    check_density_one_plus_k();
    check_density_ratio();
    check_density_rho_coeff();
    check_density_rho_den();
    check_density_rho_pow_a();
    check_density_rho_pow_p();
    check_density_rho_tic_gcc();
    check_density_rho_tic_kgm3();
    check_density_rho_tic_max();
    check_density_rho_transit_gcc();
    check_density_rho_transit_kgm3();
    check_density_tdur_max();
    check_density_vol();
    check_density_vol_coeff();
    check_density_vol_pow();
    check_depth_cons_chi_sub();
    check_depth_cons_norm_sub();
    check_depth_cons_ratio();
    check_depth_cons_sub();
    check_depth_consistency_s();
    check_depths_chi2_reduced();
    check_depths_cv();
    check_depths_err_sq();
    check_depths_mean();
    check_depths_mu_max();
    check_depths_ratio();
    check_depths_resid();
    check_depths_resid_sq();
    check_depths_std_scale();
    check_depths_std_scale2();
    check_depths_std_sqrt();
    check_depths_var_pop();
    check_geometry_cons_k_sq_max();
    check_geometry_cons_resid_abs();
    check_geometry_cons_resid_div();
    check_geometry_cons_resid_pct();
    check_geometry_cons_resid_sub();
    check_geometry_delta_clamped();
    check_geometry_k();
    check_geometry_k_sq();
    check_geometry_ld_cen_sub();
    check_geometry_ld_cen_sub2();
    check_geometry_ld_corrected();
    check_geometry_ld_i_cen();
    check_geometry_ld_i_mean();
    check_geometry_ld_numerator();
    check_geometry_ld_sub();
    check_geometry_ld_sub2();
    check_geometry_ld_u1cen_term();
    check_geometry_ld_u2cen_term();
    check_geometry_ld_zeropow();
    check_geometry_ld_zeropow_diff();
    check_geometry_rp_earth();
    check_geometry_rp_m();
    check_geometry_u1_term();
    check_geometry_u2_term();
    check_kepler_a3();
    check_kepler_a3_num();
    check_kepler_a_au();
    check_kepler_a_au_cubed();
    check_kepler_a_au_max();
    check_kepler_a_m();
    check_kepler_a_m_cubed();
    check_kepler_denominator();
    check_kepler_diff_abs();
    check_kepler_diff_si();
    check_kepler_diff_solar();
    check_kepler_diff_solar_abs();
    check_kepler_expect_max();
    check_kepler_expect_solar();
    check_kepler_expected_si();
    check_kepler_gm();
    check_kepler_gm_full();
    check_kepler_norm_diff_si();
    check_kepler_norm_solar();
    check_kepler_p_sec_sq();
    check_kepler_p_sec_sq_2();
    check_kepler_p_yr();
    check_kepler_p_yr_sq();
    check_kepler_pi_sq();
    check_kepler_ratio_si();
    check_kepler_ratio_solar();
    check_kepler_residual_si();
    check_kepler_residual_solar();
    check_probability_a_over_rs();
    check_probability_b();
    check_probability_b_clamped();
    check_probability_b_sq();
    check_probability_cos_clamped();
    check_probability_cos_max();
    check_probability_den();
    check_probability_ingress_den();
    check_probability_ingress_hrs();
    check_probability_ingress_ratio();
    check_probability_num();
    check_probability_one_plus_k();
    check_probability_opk_sq();
    check_probability_p_max();
    check_probability_ptr();
    check_probability_ptr_clamped();
    check_probability_rstar_max();
    check_probability_sin();
    check_probability_sin_arg();
    check_probability_sin_prod();
    check_probability_sin_ratio();
    check_probability_sin_term();
    check_probability_st_sq();
    check_welch_delta();
    check_welch_delta_abs();
    check_welch_delta_sigma();
    check_welch_den_max();
    check_welch_den_sqrt();
    check_welch_se();
    check_welch_se_e_sq();
    check_welch_se_o_sq();
    check_welch_sqrt_n();
    check_welch_var_sum();
    return 0;
}